// Concept D copy — strings unique to this design direction.
// Shared wording (bid, watch, grades …) comes from data/ui.js via ui().

export const COPY = {
  // Chrome
  skipToContent: { en: "Skip to content", ar: "تخطَّ إلى المحتوى" },
  homeLink: { en: "Khazna home", ar: "الصفحة الرئيسية لخزنة" },
  primaryNav: { en: "Marketplace sections", ar: "أقسام السوق" },
  discover: { en: "Discover", ar: "اكتشف" },
  commandSearch: { en: "Search lots, sellers, categories", ar: "ابحث في المنتجات والبائعين والفئات" },
  commandSearchShort: { en: "Search", ar: "بحث" },
  openSearch: { en: "Open search", ar: "فتح البحث" },
  liveWatching: { en: "Live · {n} watching", ar: "مباشر · {n} مشاهد" },
  enterLive: { en: "Live auction room", ar: "غرفة المزاد المباشر" },
  walletMenu: { en: "Wallet balance {amount}", ar: "رصيد المحفظة {amount}" },
  accountMenu: { en: "Account menu", ar: "قائمة الحساب" },
  cartButton: { en: "Cart, {n} items", ar: "السلة، {n} منتجات" },
  buyerAccount: { en: "Buyer account", ar: "حساب مشترٍ" },
  depositLabel: { en: "Bidding deposit", ar: "تأمين المزايدة" },
  biddingStatus: { en: "Bidding", ar: "المزايدة" },
  readyToBid: { en: "Ready to bid", ar: "جاهز للمزايدة" },
  topUpToBid: { en: "Top up to bid", ar: "اشحن للمزايدة" },
  topUp: { en: "Top up wallet", ar: "اشحن المحفظة" },
  topUpToast: { en: "Top up by card — mada, Visa or Mastercard.", ar: "اشحن بالبطاقة — مدى أو فيزا أو ماستركارد." },
  walletNote: { en: "Keep enough balance to cover the refundable bidding deposit.", ar: "احرص على أن يغطي رصيدك تأمين المزايدة المسترد." },
  signOut: { en: "Sign out", ar: "تسجيل الخروج" },
  signedOutToast: { en: "You'll stay signed in for this preview.", ar: "ستبقى مسجلاً للدخول خلال هذا العرض." },
  myBidsToast: { en: "Every lot you bid on appears here with its live status.", ar: "تظهر هنا كل المنتجات التي زايدت عليها مع حالتها المباشرة." },
  watchlistToast: { en: "{n} lots saved to your watchlist.", ar: "{n} منتجات محفوظة في قائمة متابعتك." },
  ordersToast: { en: "Won lots are paid within 24 hours, then collected or delivered.", ar: "تُدفع المنتجات الفائزة خلال 24 ساعة، ثم تُستلم أو تُوصّل." },
  notificationsToast: { en: "Outbid, leading-bid and watched-lot activity notifications appear here.", ar: "تظهر هنا إشعارات تجاوز مزايدتك وتصدّرك ونشاط المنتجات التي تتابعها." },
  cartEmpty: { en: "Your cart is empty", ar: "سلتك فارغة" },
  cartEmptyText: { en: "Buy Now items you add will wait here for checkout.", ar: "ستنتظرك هنا منتجات الشراء الفوري التي تضيفها حتى إتمام الشراء." },
  subtotal: { en: "Subtotal", ar: "المجموع الفرعي" },
  checkoutToast: { en: "Confirm delivery or pickup, then pay by card (mada, Visa or Mastercard) or from your wallet.", ar: "أكّد التوصيل أو الاستلام، ثم ادفع بالبطاقة (مدى أو فيزا أو ماستركارد) أو من محفظتك." },
  remove: { en: "Remove", ar: "إزالة" },
  linkElsewhere: { en: "This page isn't included in this preview.", ar: "هذه الصفحة غير مشمولة في هذا العرض." },
  appearance: { en: "Appearance", ar: "المظهر" },
  ctrlK: { en: "Ctrl K", ar: "Ctrl K" },

  // Command palette
  paletteTitle: { en: "Search Khazna", ar: "البحث في خزنة" },
  paletteLots: { en: "Lots", ar: "المنتجات" },
  paletteCategories: { en: "Categories", ar: "الفئات" },
  paletteSellers: { en: "Sellers", ar: "البائعون" },
  paletteClosing: { en: "Closing soon", ar: "تُغلق قريباً" },
  paletteSeeAll: { en: "See all results for “{q}”", ar: "عرض كل نتائج «{q}»" },
  paletteNoResults: { en: "No matches for “{q}”", ar: "لا توجد نتائج لـ «{q}»" },
  paletteNoResultsText: { en: "Try a lot number like KZ-0352, a category or a seller name.", ar: "جرّب رقم منتج مثل KZ-0352 أو اسم فئة أو بائع." },
  paletteNavigate: { en: "to navigate", ar: "للتنقل" },
  paletteOpen: { en: "to open", ar: "للفتح" },
  paletteClose: { en: "to close", ar: "للإغلاق" },

  // Ticker
  tickerLabel: { en: "Latest bids across the marketplace", ar: "أحدث المزايدات في السوق" },
  tickerTitle: { en: "Live bids", ar: "مزايدات مباشرة" },
  pauseTicker: { en: "Pause live bids", ar: "إيقاف المزايدات المتحركة مؤقتاً" },
  playTicker: { en: "Resume live bids", ar: "استئناف المزايدات المتحركة" },

  // Home
  marketOpen: { en: "Bidding open", ar: "المزايدة مفتوحة" },
  auctionsLive: { en: "{n} auctions running", ar: "{n} مزادات جارية" },
  featuredLot: { en: "Featured lot", ar: "منتج مميز" },
  priceHistory: { en: "Price history", ar: "مسار السعر" },
  recentBids: { en: "Recent bids", ar: "أحدث المزايدات" },
  sinceOpening: { en: "since opening", ar: "منذ الافتتاح" },
  openLot: { en: "Open lot", ar: "افتح المنتج" },
  closingBoardTitle: { en: "Closing soon", ar: "تُغلق قريباً" },
  closingBoardText: { en: "The six auctions nearest their close, updating as bids land.", ar: "أقرب ستة مزادات إلى الإغلاق، تتحدّث مع كل مزايدة جديدة." },
  colItem: { en: "Item", ar: "المنتج" },
  colBids: { en: "Bids", ar: "المزايدات" },
  colWatching: { en: "Watching", ar: "المتابعون" },
  colPrice: { en: "Price", ar: "السعر" },
  colStatus: { en: "Status", ar: "الحالة" },
  colStock: { en: "Stock", ar: "المخزون" },
  colAmount: { en: "Amount", ar: "المبلغ" },
  colTime: { en: "Time", ar: "الوقت" },
  bid: { en: "Bid", ar: "زايد" },
  view: { en: "View", ar: "عرض" },
  liveEventsTitle: { en: "Live & upcoming sales", ar: "المزادات المباشرة والقادمة" },
  liveEventsText: { en: "Presenter-led sales with live bidding, streamed from seller warehouses.", ar: "مزادات يقدّمها مذيع مع مزايدة لحظية، تُبث من مستودعات البائعين." },
  lotProgress: { en: "Lot {n} of {total}", ar: "المنتج {n} من {total}" },
  trendingTitle: { en: "Trending auctions", ar: "المزادات الرائجة" },
  trendingText: { en: "Ranked by bidding activity right now.", ar: "مرتّبة حسب نشاط المزايدة الآن." },
  categoriesText: { en: "Live lot counts across every category.", ar: "أعداد المنتجات المعروضة في كل فئة." },
  lotsCount: { en: "{n} lots", ar: "{n} منتج" },
  instantTitle: { en: "Instant buy", ar: "اشترِ فوراً" },
  instantText: { en: "Fixed prices on graded stock — no bidding; choose delivery or pickup at checkout.", ar: "أسعار ثابتة لمخزون مصنّف — دون مزايدة؛ اختر التوصيل أو الاستلام عند الدفع." },
  bulkText: { en: "Full pallets and cartons with line-by-line manifests.", ar: "طبليات وكراتين كاملة ببيان تفصيلي لكل بند." },
  manifestLines: { en: "{n} lines", ar: "{n} بنود" },
  perUnit: { en: "≈ {amount} per unit", ar: "≈ {amount} للقطعة" },
  cartonOf: { en: "Carton of {n}", ar: "كرتونة من {n}" },
  caseOf: { en: "Case of {n}", ar: "كرتونة من {n}" },
  warehousesText: { en: "Every storefront belongs to a seller warehouse on Khazna.", ar: "كل متجر يعود لمستودع بائع على خزنة." },
  colWarehouse: { en: "Warehouse", ar: "المستودع" },
  colCity: { en: "City", ar: "المدينة" },
  colSince: { en: "On Khazna since", ar: "على خزنة منذ" },
  metricsTitle: { en: "Khazna in numbers", ar: "خزنة بالأرقام" },
  metricsText: { en: "Headline figures from the Khazna About page.", ar: "أرقام رئيسية من صفحة «عن خزنة»." },
  gradesTitle: { en: "One grade scale, disclosed on every lot", ar: "مقياس درجات واحد، معلن على كل منتج" },
  step: { en: "Step {n}", ar: "الخطوة {n}" },

  // Cards & data
  lastMove: { en: "Last bid +{amount}", ar: "آخر زيادة +{amount}" },
  velocity: { en: "{n} bids · last 10 min", ar: "{n} مزايدات · آخر 10 دقائق" },
  velocityOne: { en: "1 bid · last 10 min", ar: "مزايدة واحدة · آخر 10 دقائق" },
  velocityNone: { en: "Quiet · last 10 min", ar: "هادئ · آخر 10 دقائق" },
  heatLabel: { en: "Bidding activity: {level} of 4", ar: "نشاط المزايدة: {level} من 4" },
  timeLeftAria: { en: "{time} left", ar: "متبقٍ {time}" },
  startsInAria: { en: "Starts in {time}", ar: "يبدأ خلال {time}" },
  priceChartLabel: { en: "Bid price rose from {from} to {to} across {n} bids.", ar: "ارتفع سعر المزايدة من {from} إلى {to} عبر {n} مزايدات." },
  priceChartEmpty: { en: "No bids yet — the chart starts with the first bid.", ar: "لا مزايدات بعد — يبدأ الرسم مع أول مزايدة." },
  sparkLabel: { en: "Recent price trend", ar: "اتجاه السعر مؤخراً" },
  perCaseShort: { en: "/ case", ar: "/ كرتونة" },
  stockLabel: { en: "Stock level", ar: "مستوى المخزون" },
  watched: { en: "Saved", ar: "محفوظ" },
  finalPrice: { en: "Final price", ar: "السعر النهائي" },
  opensAt: { en: "Opens at", ar: "يفتح عند" },
  endedAt: { en: "Closed", ar: "أُغلق" },

  // Browse
  browseTitleAll: { en: "All lots", ar: "كل المنتجات" },
  browseTitleAuction: { en: "Auctions", ar: "المزادات" },
  browseTitleBuy: { en: "Buy Now", ar: "الشراء الفوري" },
  browseText: { en: "Graded surplus and returned stock from Saudi warehouses.", ar: "فائض مخزون ومرتجعات مصنّفة من مستودعات سعودية." },
  saleType: { en: "Sale type", ar: "نوع البيع" },
  viewMode: { en: "View", ar: "طريقة العرض" },
  hideFilters: { en: "Hide filters", ar: "إخفاء عوامل التصفية" },
  showFilters: { en: "Show filters", ar: "إظهار عوامل التصفية" },
  loadMoreCount: { en: "Load {n} more", ar: "عرض {n} أخرى" },
  allLoaded: { en: "You've seen every lot", ar: "شاهدت جميع المنتجات" },
  activeFilters: { en: "Active filters", ar: "عوامل التصفية النشطة" },
  removeFilter: { en: "Remove filter: {label}", ar: "إزالة عامل التصفية: {label}" },
  searchFor: { en: "“{q}”", ar: "«{q}»" },
  priceFrom: { en: "{min} – {max}", ar: "{min} – {max}" },
  scanning: { en: "Scanning the marketplace", ar: "جارٍ البحث في السوق" },
  emptyPopular: { en: "Popular right now", ar: "الأكثر بحثاً الآن" },

  // Detail pages
  lotNo: { en: "Lot {n}", ar: "المنتج {n}" },
  endsAt: { en: "Ends {date}", ar: "ينتهي {date}" },
  startsAt: { en: "Opens {date}", ar: "يفتح {date}" },
  bidsBidders: { en: "Bids", ar: "المزايدات" },
  biddersLabel: { en: "Bidders", ar: "المزايدون" },
  watchingLabel: { en: "Watching", ar: "المتابعون" },
  customAmount: { en: "Your bid amount", ar: "قيمة مزايدتك" },
  lowerBid: { en: "Lower bid by one increment", ar: "خفّض المزايدة بزيادة واحدة" },
  raiseBid: { en: "Raise bid by one increment", ar: "ارفع المزايدة بزيادة واحدة" },
  reviewBid: { en: "Review bid", ar: "مراجعة المزايدة" },
  maxBidActive: { en: "Auto-bidding up to {amount}", ar: "مزايدة تلقائية حتى {amount}" },
  maxBidSlider: { en: "Maximum bid amount", ar: "قيمة الحد الأقصى" },
  walletLine: { en: "Wallet {amount}", ar: "المحفظة {amount}" },
  purchasedTitle: { en: "You bought this lot", ar: "اشتريت هذا المنتج" },
  purchasedText: { en: "The auction is closed. Choose pickup or delivery at checkout.", ar: "أُغلق المزاد. اختر الاستلام أو التوصيل عند إتمام الشراء." },
  purchasedToast: { en: "Bought with Buy Now — the auction is now closed.", ar: "تم الشراء الفوري — أُغلق المزاد الآن." },
  confirmPurchase: { en: "Confirm purchase", ar: "تأكيد الشراء" },
  payNow: { en: "Pay now", ar: "ادفع الآن" },
  wonText: { en: "Payment is due within 24 hours. Choose pickup or delivery at checkout.", ar: "الدفع مستحق خلال 24 ساعة. اختر الاستلام أو التوصيل عند إتمام الشراء." },
  outbidText: { en: "Place a new bid to take the lead again.", ar: "قدّم مزايدة جديدة لتستعيد الصدارة." },
  highestText: { en: "You'll get a notification if someone outbids you.", ar: "سيصلك إشعار إذا تجاوز أحد مزايدتك." },
  lostText: { en: "Another bidder won this lot. Similar auctions are below.", ar: "فاز مزايد آخر بهذا المنتج. تجد مزادات مشابهة أدناه." },
  endedText: { en: "Bidding has closed on this lot.", ar: "أُغلقت المزايدة على هذا المنتج." },
  soldText: { en: "This lot sold at auction. Browse similar lots below.", ar: "بيع هذا المنتج في المزاد. تصفّح منتجات مشابهة أدناه." },
  upcomingText: { en: "Bidding hasn't opened yet. Watch this lot to keep it in your watchlist.", ar: "لم تبدأ المزايدة بعد. تابع هذا المنتج ليبقى في قائمة متابعتك." },
  marketCompare: { en: "Market comparison", ar: "مقارنة بسعر السوق" },
  atMarket: { en: "At or above market price", ar: "عند سعر السوق أو أعلى" },
  buyNowMarker: { en: "Buy Now", ar: "الشراء الفوري" },
  details: { en: "Details", ar: "التفاصيل" },
  seller: { en: "Seller", ar: "البائع" },
  highlights: { en: "Highlights", ar: "أبرز المزايا" },
  termDeposit: { en: "Refundable bidding deposit", ar: "تأمين مزايدة مسترد" },
  termExtension: { en: "Anti-sniping extension", ar: "التمديد ضد المزايدة الخاطفة" },
  termExtensionValue: { en: "+5 min for bids in the last 5 min", ar: "+5 دقائق للمزايدات في آخر 5 دقائق" },
  termPayment: { en: "Payment window", ar: "مهلة الدفع" },
  termPaymentValue: { en: "24 hours after winning", ar: "24 ساعة بعد الفوز" },
  termBinding: { en: "Bids", ar: "المزايدات" },
  termBindingValue: { en: "Binding once placed", ar: "ملزمة بعد تقديمها" },
  manifestTotal: { en: "{n} units across {lines} lines", ar: "{n} قطعة موزعة على {lines} بنود" },
  manifestChart: { en: "Units per manifest line", ar: "عدد القطع في كل بند" },
  share: { en: "Share of lot", ar: "الحصة من الدفعة" },
  imageStage: { en: "Product images", ar: "صور المنتج" },
  thumbnails: { en: "Choose an image", ar: "اختر صورة" },
  closeViewer: { en: "Close image viewer", ar: "إغلاق عارض الصور" },
  youSave: { en: "You save {amount}", ar: "توفّر {amount}" },
  fullLot: { en: "Full lot", ar: "دفعة كاملة" },
  cases: { en: "cases", ar: "كراتين" },
  soldOutText: { en: "Sold out. Similar items are shown below.", ar: "نفدت الكمية. تجد منتجات مشابهة أدناه." },
  inspectedLine: { en: "The condition grade is shown on the listing.", ar: "درجة الحالة معروضة في صفحة المنتج." },
  deliveryAndReturns: { en: "Delivery, pickup and returns", ar: "التوصيل والاستلام والإرجاع" },
  totalFor: { en: "Total for {n}", ar: "الإجمالي لـ {n}" },

  // Live
  liveRoom: { en: "Live room", ar: "غرفة المزاد" },
  lotQueue: { en: "Lot queue", ar: "قائمة المنتجات" },
  console: { en: "Bidding console", ar: "لوحة المزايدة" },
  hammerSold: { en: "Hammer down", ar: "رسا المزاد" },
  notSoldText: { en: "Not sold", ar: "لم يُبع" },
  lotLive: { en: "On the block", ar: "المعروض الآن" },
  opensAtBid: { en: "Opens {amount}", ar: "يبدأ من {amount}" },
  liveDeposit: { en: "Live-sale deposit {amount}", ar: "تأمين المزاد المباشر {amount}" },
  presenter: { en: "Presenter", ar: "المقدّم" },
  host: { en: "Host warehouse", ar: "المستودع المستضيف" },
  youWonLot: { en: "You won this lot", ar: "فزت بهذا المنتج" },
  noActivity: { en: "Bids will appear here the moment they land.", ar: "ستظهر المزايدات هنا فور تقديمها." },
  streamAlt: { en: "Live stream from the Red Sea Trading warehouse", ar: "بث مباشر من مستودع شركة البحر الأحمر للتجارة" },
  lotTab: { en: "Lot", ar: "المنتج" },
  intermission: { en: "Next lot in {n}s", ar: "المنتج التالي خلال {n} ث" },
  startedAgo: { en: "Started {n} min ago", ar: "بدأ قبل {n} دقيقة" },

  // Seller
  storeStats: { en: "Store at a glance", ar: "المتجر بلمحة" },
  categoriesStat: { en: "Categories", ar: "الفئات" },
  listingsStat: { en: "Live listings", ar: "المعروضات الحالية" },
  trustGraded: { en: "Condition grade on every listing", ar: "درجة حالة لكل منتج معروض" },
  trustStorefront: { en: "Public storefront on Khazna", ar: "متجر عام على خزنة" },
  trustPickup: { en: "Pickup or delivery, priced at checkout", ar: "استلام أو توصيل بتكلفة تُحدد عند الدفع" },
  platformBadge: { en: "Khazna-owned stock", ar: "مخزون مملوك لخزنة" },
  otherWarehouses: { en: "More seller warehouses", ar: "مستودعات بائعين أخرى" },
  storeLinkCopied: { en: "Store link copied", ar: "تم نسخ رابط المتجر" },
  watchLive: { en: "Watch live", ar: "شاهد البث" },

  // System board
  systemTitle: { en: "Components & states", ar: "المكونات والحالات" },
  systemText: {
    en: "The building blocks of the Digital / Auction direction — tokens, type, controls, data visualisations and every listing state — in both appearances.",
    ar: "مكونات اتجاه «سوق المزادات الرقمي» — الألوان والخطوط وعناصر التحكم والرسوم البيانية وجميع حالات المنتجات — بالمظهرين الداكن والفاتح.",
  },
  sysColour: { en: "Colour tokens", ar: "رموز الألوان" },
  sysDark: { en: "Dark (default)", ar: "داكن (افتراضي)" },
  sysLight: { en: "Light", ar: "فاتح" },
  sysType: { en: "Type scale", ar: "مقياس الخطوط" },
  sysButtons: { en: "Buttons", ar: "الأزرار" },
  sysInputs: { en: "Inputs", ar: "حقول الإدخال" },
  sysBadges: { en: "Status & grade badges", ar: "شارات الحالة والدرجة" },
  sysData: { en: "Data visualisation", ar: "عرض البيانات" },
  sysCards: { en: "Listing cards", ar: "بطاقات المنتجات" },
  sysFeedback: { en: "Feedback & overlays", ar: "التنبيهات والنوافذ" },
  sysNavigation: { en: "Navigation patterns", ar: "أنماط التنقل" },
  stDefault: { en: "Default", ar: "افتراضي" },
  stHover: { en: "Hover", ar: "تمرير" },
  stActive: { en: "Active", ar: "نشط" },
  stFocus: { en: "Focus", ar: "تركيز" },
  stDisabled: { en: "Disabled", ar: "معطّل" },
  stLoading: { en: "Loading", ar: "تحميل" },
  stError: { en: "Error", ar: "خطأ" },
  stFocused: { en: "Focused", ar: "مُركّز" },
  typeDisplay: { en: "Display", ar: "عنوان رئيسي" },
  typeHeading: { en: "Heading", ar: "عنوان" },
  typeBody: { en: "Body", ar: "نص" },
  typeLabel: { en: "Label", ar: "تسمية" },
  typeFigures: { en: "Figures", ar: "الأرقام" },
  sampleBody: {
    en: "Every lot shows its condition grade.",
    ar: "لكل منتج درجة حالة معلنة.",
  },
  ringNormal: { en: "Running", ar: "جارٍ" },
  sampleCardLive: { en: "Live auction", ar: "مزاد مباشر" },
  sampleCardWatched: { en: "Saved to watchlist", ar: "محفوظ في المتابعة" },
  sampleCardEnded: { en: "Ended", ar: "انتهى" },
  toastSuccess: { en: "Success toast", ar: "تنبيه نجاح" },
  toastWarning: { en: "Warning toast", ar: "تنبيه تحذير" },
  toastInfo: { en: "Info toast", ar: "تنبيه معلومات" },
  toastNeutral: { en: "Neutral toast", ar: "تنبيه محايد" },
  openModal: { en: "Open modal", ar: "فتح نافذة" },
  openDrawer: { en: "Open filter drawer", ar: "فتح درج التصفية" },
  openMenu: { en: "Open mobile menu", ar: "فتح قائمة الجوال" },
  modalDemoTitle: { en: "Bids are binding", ar: "المزايدات ملزمة" },
  emailPlaceholder: { en: "name@company.sa", ar: "name@company.sa" },
  pageOf: { en: "Page {n} of {total}", ar: "الصفحة {n} من {total}" },
  grpSurfaces: { en: "Surfaces", ar: "الأسطح" },
  grpText: { en: "Text", ar: "النصوص" },
  grpBrand: { en: "Brand & action", ar: "الهوية والإجراءات" },
  grpStatus: { en: "Status", ar: "الحالات" },
  grpGrades: { en: "Condition grades", ar: "درجات الحالة" },
  tkPage: { en: "Page", ar: "الصفحة" },
  tkSurface: { en: "Surface", ar: "السطح" },
  tkRaised: { en: "Raised", ar: "مرتفع" },
  tkElevated: { en: "Elevated", ar: "بارز" },
  tkPlate: { en: "Product plate", ar: "خلفية المنتج" },
  tkLine: { en: "Line", ar: "خط" },
  tkLineStrong: { en: "Line strong", ar: "خط بارز" },
  tkText: { en: "Primary", ar: "أساسي" },
  tkText2: { en: "Secondary", ar: "ثانوي" },
  tkText3: { en: "Muted", ar: "خافت" },
  tkIndigo: { en: "Indigo action", ar: "النيلي للإجراءات" },
  tkInk: { en: "Indigo ink", ar: "حبر نيلي" },
  tkGold: { en: "Gold — your bid", ar: "الذهبي — مزايدتك" },
  tkGoldInk: { en: "Gold ink", ar: "حبر ذهبي" },
  tkLive: { en: "Live", ar: "مباشر" },
  tkSuccess: { en: "Success", ar: "نجاح" },
  tkWarning: { en: "Warning", ar: "تحذير" },
  tkDanger: { en: "Danger", ar: "خطر" },
  sysFontLatin: { en: "Geist · Geist Mono", ar: "Geist · Geist Mono" },
  sysFontArabic: { en: "Readex Pro", ar: "ريدكس برو" },
  sysRings: { en: "Countdown rings by urgency", ar: "حلقات العد التنازلي حسب الإلحاح" },
  sysBars: { en: "Time bars", ar: "أشرطة الوقت" },
  sysChart: { en: "Bid step chart (hover for each bid)", ar: "رسم مراحل المزايدة (مرّر لعرض كل مزايدة)" },
  sysStock: { en: "Stock meters", ar: "مؤشرات المخزون" },
  sysManifest: { en: "Manifest bar", ar: "شريط البيان" },
  sysHeat: { en: "Heat, sparkline & deltas", ar: "النشاط والاتجاه والتغيّر" },
  sysSkeleton: { en: "Loading skeleton", ar: "هيكل التحميل" },
  sysEmpty: { en: "Empty state", ar: "حالة فارغة" },
  sysToasts: { en: "Toasts", ar: "التنبيهات" },
  sysOverlays: { en: "Modal, dropdown & drawers", ar: "النوافذ والقوائم والأدراج" },
  sysPaging: { en: "Pagination & load more", ar: "ترقيم الصفحات وعرض المزيد" },
  sysOverlayChips: { en: "On photography", ar: "فوق الصور" },
  sysSoftChips: { en: "In panels", ar: "داخل اللوحات" },
  sysDisabledNote: { en: "Disabled", ar: "معطّل" },
  sysDeltas: { en: "Deltas & lot numbers", ar: "التغيّرات وأرقام المنتجات" },
  vGold: { en: "Gold · bid", ar: "ذهبي · مزايدة" },
  vPrimary: { en: "Indigo · action", ar: "نيلي · إجراء" },
  vSecondary: { en: "Secondary", ar: "ثانوي" },
  vGhost: { en: "Quiet", ar: "هادئ" },
  demoToastTitle: { en: "Bid placed — you're the highest bidder", ar: "تم تقديم المزايدة — أنت صاحب أعلى مزايدة" },
};
