// Option 2 — Visual Marketplace (Round 3): copy unique to this design.
// Shared marketplace strings live in data/ui.js; shared content (hero,
// trust points, how it works, footer) lives in data/site.js.

export const COPY = {
  skip: { en: "Skip to content", ar: "انتقل إلى المحتوى" },
  home: { en: "Khazna home", ar: "الصفحة الرئيسية لخزنة" },
  primaryNav: { en: "Shop", ar: "تسوّق" },
  secondaryNav: { en: "Live and sellers", ar: "المباشر والبائعون" },
  accountNav: { en: "Your account and bag", ar: "حسابك وحقيبتك" },

  // Hero
  searchLabel: { en: "Search Khazna", ar: "ابحث في خزنة" },
  searchPlaceholder: { en: "What are you looking for?", ar: "عمّ تبحث اليوم؟" },
  popular: { en: "Popular", ar: "الأكثر بحثاً" },
  trustGrade: { en: "Condition grade on every lot", ar: "درجة حالة معلنة لكل منتج" },
  trustDelivery: { en: "Delivery priced at checkout", ar: "تُحسب تكلفة التوصيل عند إتمام الشراء" },
  allCategories: { en: "All categories", ar: "كل الفئات" },

  // Sections
  featuredNow: { en: "Featured now", ar: "مميز الآن" },
  mosaicTitle: { en: "Shop by category, or by seller", ar: "تسوّق حسب الفئة أو البائع" },
  mosaicSub: { en: "Eight departments and the warehouses behind them", ar: "ثماني فئات والمستودعات التي تقف خلفها" },
  featuredTitle: { en: "Featured on Khazna", ar: "مميز على خزنة" },
  featuredSub: { en: "A mix of fixed-price stock and open auctions", ar: "مزيج من مخزون بسعر ثابت ومزادات مفتوحة" },
  onTheBlock: { en: "On the block", ar: "في المزاد الآن" },
  onTheBlockSub: { en: "Timed auctions, closing soonest first", ar: "مزادات محددة المدة، الأقرب إغلاقاً أولاً" },
  seeAllAuctions: { en: "See all {n} auctions", ar: "عرض كل المزادات ({n})" },
  readyToBuy: { en: "Ready to buy", ar: "جاهز للشراء" },
  readyToBuySub: { en: "Fixed prices, the biggest savings first", ar: "أسعار ثابتة، الأكبر توفيراً أولاً" },
  shopAll: { en: "Shop all {n}", ar: "تسوّق الكل ({n})" },
  gradesTitle: { en: "Every lot carries a condition grade", ar: "لكل منتج درجة حالة" },
  gradesSub: { en: "From New to F — read the grade before you bid or buy.", ar: "من «جديد» حتى F — اطّلع على الدرجة قبل أن تزايد أو تشتري." },
  gradeGuide: { en: "Full grade guide", ar: "دليل الدرجات الكامل" },
  howTitle: { en: "How Khazna works", ar: "كيف تعمل خزنة" },

  // Lots
  openForBids: { en: "Open for bids", ar: "مفتوح للمزايدة" },
  opensIn: { en: "Opens in {time}", ar: "يفتح خلال {time}" },
  closesIn: { en: "Closes in {time}", ar: "يُغلق خلال {time}" },
  currentBid: { en: "Current bid", ar: "المزايدة الحالية" },
  placeBid: { en: "Place bid", ar: "قدّم مزايدة" },
  viewLot: { en: "View lot", ar: "عرض المنتج" },
  addToBag: { en: "Add to bag", ar: "أضف إلى الحقيبة" },
  addNamed: { en: "Add {title} to bag", ar: "أضف {title} إلى الحقيبة" },
  addedToBag: { en: "Added to your bag", ar: "أُضيف إلى حقيبتك" },
  auction: { en: "Auction", ar: "مزاد" },
  upcoming: { en: "Upcoming", ar: "قادم" },
  soldOut: { en: "Sold out", ar: "نفدت الكمية" },
  inStock: { en: "{n} in stock", ar: "{n} متوفرة" },
  manifest: { en: "{n} units inside", ar: "{n} قطعة بالداخل" },
  lotsIn: { en: "{n} lots", ar: "{n} منتج" },
  sellerLots: { en: "{n} lots · {city}", ar: "{n} منتج · {city}" },
  hosting: { en: "Hosting a live sale now", ar: "يستضيف مزاداً مباشراً الآن" },
  live: { en: "Live", ar: "مباشر" },

  // Header & overlays
  categories: { en: "Categories", ar: "الفئات" },
  browseCategories: { en: "Browse Khazna", ar: "تصفّح خزنة" },
  sellersRow: { en: "Shop a seller's warehouse", ar: "تسوّق من مستودع بائع" },
  waysToShop: { en: "Ways to shop", ar: "طرق التسوّق" },
  searchTitle: { en: "Search Khazna", ar: "ابحث في خزنة" },
  searchShort: { en: "Search", ar: "بحث" },
  searchResultsLots: { en: "Lots", ar: "المنتجات" },
  searchResultsCats: { en: "Categories", ar: "الفئات" },
  searchResultsSellers: { en: "Sellers", ar: "البائعون" },
  searchNoMatch: { en: "No lots match “{q}” yet — try another word.", ar: "لا توجد منتجات تطابق «{q}» — جرّب كلمة أخرى." },
  searchSeeAll: { en: "See all results for “{q}”", ar: "عرض كل نتائج «{q}»" },
  searchBrowse: { en: "Or start from a category", ar: "أو ابدأ من فئة" },
  menu: { en: "Menu", ar: "القائمة" },
  openMenu: { en: "Open menu", ar: "فتح القائمة" },
  close: { en: "Close", ar: "إغلاق" },
  watchlistCount: { en: "Watchlist, {n} saved", ar: "قائمة المتابعة، {n} محفوظ" },
  bagCount: { en: "Bag, {n} items", ar: "الحقيبة، {n} منتج" },
  yourBag: { en: "Your bag", ar: "حقيبتك" },
  bagEmpty: { en: "Your bag is empty", ar: "حقيبتك فارغة" },
  bagEmptyText: { en: "Fixed-price lots you add appear here.", ar: "تظهر هنا المنتجات ذات السعر الثابت التي تضيفها." },
  subtotal: { en: "Subtotal", ar: "المجموع الفرعي" },
  remove: { en: "Remove", ar: "إزالة" },
  removed: { en: "Removed from your bag", ar: "أُزيل من حقيبتك" },
  checkoutTitle: { en: "Secure checkout", ar: "إتمام شراء آمن" },
  continueShopping: { en: "Continue shopping", ar: "متابعة التسوّق" },
  account: { en: "Account", ar: "الحساب" },
  accountMenu: { en: "Account menu", ar: "قائمة الحساب" },
  hello: { en: "Hello, {name}", ar: "مرحباً، {name}" },
  walletBalance: { en: "Wallet balance", ar: "رصيد المحفظة" },
  myBids: { en: "My bids", ar: "مزايداتي" },
  orders: { en: "Orders", ar: "الطلبات" },
  watchlist: { en: "Watchlist", ar: "قائمة المتابعة" },
  notifications: { en: "Notifications", ar: "الإشعارات" },
  country: { en: "Country", ar: "الدولة" },
  saudiArabia: { en: "Saudi Arabia", ar: "المملكة العربية السعودية" },
  language: { en: "Language", ar: "اللغة" },
  switchLanguage: { en: "العربية", ar: "English" },
  switchLanguageLabel: { en: "Switch to Arabic", ar: "التبديل إلى الإنجليزية" },
  myBidsText: { en: "Bids you place appear here with their live status.", ar: "تظهر هنا مزايداتك مع حالتها المباشرة." },
  ordersText: { en: "You have no orders yet.", ar: "لا توجد لديك طلبات بعد." },
  notificationsText: { en: "You're all caught up.", ar: "لا توجد إشعارات جديدة." },
  walletText: { en: "Covers the bidding deposit.", ar: "يغطي تأمين المزايدة." },
  watchlistEmpty: { en: "No saved lots yet", ar: "لا توجد منتجات محفوظة بعد" },
  watchlistEmptyText: { en: "Tap the heart on any lot to follow its price and closing time.", ar: "اضغط على القلب في أي منتج لمتابعة سعره ووقت إغلاقه." },
  browseLots: { en: "Browse lots", ar: "تصفّح المنتجات" },
  openCategories: { en: "Open the categories overlay", ar: "فتح لوحة الفئات" },
  lotsCount: { en: "{n} lots", ar: "{n} منتج" },
  openAuctions: { en: "{n} open auctions", ar: "{n} مزادات مفتوحة" },
  buyNowItems: { en: "{n} fixed-price lots", ar: "{n} منتجاً بسعر ثابت" },
  liveNowCount: { en: "1 live sale now", ar: "مزاد مباشر واحد الآن" },
  sellersLine: { en: "{n} seller warehouses", ar: "{n} مستودعات بائعين" },
  palletsLine: { en: "Full pallets and cartons", ar: "طبليات وكراتين كاملة" },
  visitSeller: { en: "Visit {name}", ar: "زيارة {name}" },
  liveHosting: { en: "Live now", ar: "مباشر الآن" },

  // Live mini-player
  liveRegion: { en: "Live auction now", ar: "مزاد مباشر الآن" },
  lotOf: { en: "Lot {n} of {total}", ar: "المنتج {n} من {total}" },
  join: { en: "Join", ar: "انضم" },
  joinLive: { en: "Join the live sale", ar: "انضم إلى المزاد المباشر" },
  hidePlayer: { en: "Minimise live player", ar: "تصغير مشغّل البث" },
  showPlayer: { en: "Show the live sale", ar: "عرض المزاد المباشر" },

  // Footer
  newsletterTitle: { en: "Closing-soon alerts by email", ar: "تنبيهات المزادات القريبة من الإغلاق عبر البريد" },
  emailLabel: { en: "Email address", ar: "البريد الإلكتروني" },
  countryLine: { en: "Shipping to Saudi Arabia", ar: "الشحن داخل المملكة العربية السعودية" },
  footerTag: { en: "Graded returns, surplus and pallets from Saudi warehouses.", ar: "مرتجعات وفائض مخزون وطبليات مصنّفة من مستودعات سعودية." },
  weAccept: { en: "We accept", ar: "نقبل" },
};
