// Copy that only exists in Concept C (section titles, helper lines).
// Shared wording (buttons, statuses, labels) comes from data/ui.js via ui().

export const COPY = {
  // Chrome
  skip: { en: "Skip to main content", ar: "انتقل إلى المحتوى الرئيسي" },
  mainNav: { en: "Main navigation", ar: "التنقل الرئيسي" },
  utilityNav: { en: "Service links", ar: "روابط الخدمة" },
  footerNav: { en: "Footer links", ar: "روابط التذييل" },
  openSearch: { en: "Open search", ar: "فتح البحث" },
  closeSearch: { en: "Close search", ar: "إغلاق البحث" },
  topMatches: { en: "Top matches", ar: "أقرب النتائج" },
  noMatches: { en: "No direct matches yet — search all lots instead.", ar: "لا توجد نتائج مطابقة بعد — ابحث في كل المعروض." },
  searchAll: { en: "See all results for “{q}”", ar: "عرض كل نتائج «{q}»" },
  searchHint: { en: "Try a product, a brand or a lot number", ar: "جرّب اسم منتج أو علامة تجارية أو رقم منتج" },
  buyerAccount: { en: "Buyer account", ar: "حساب مشترٍ" },
  signOut: { en: "Sign out", ar: "تسجيل الخروج" },
  cartEmpty: { en: "Your cart is empty", ar: "سلتك فارغة" },
  cartEmptyText: { en: "Fixed-price lots you add will appear here.", ar: "ستظهر هنا منتجات الشراء الفوري التي تضيفها." },
  subtotal: { en: "Subtotal", ar: "المجموع الفرعي" },
  remove: { en: "Remove", ar: "إزالة" },
  checkoutNote: {
    en: "Pay by card (mada, Visa or Mastercard) on a secure payment page, or with your Khazna wallet.",
    ar: "ادفع بالبطاقة (مدى أو فيزا أو ماستركارد) عبر صفحة دفع آمنة، أو من محفظة خزنة.",
  },
  watchEmpty: { en: "Your watchlist is empty", ar: "قائمة متابعتك فارغة" },
  watchEmptyText: {
    en: "Tap the bookmark on any lot to follow its price and closing time.",
    ar: "اضغط رمز الحفظ على أي منتج لتتابع سعره وموعد إغلاقه.",
  },
  pageSoon: { en: "This page is being prepared.", ar: "يجري إعداد هذه الصفحة." },
  helpText: { en: "Our team answers Sunday to Thursday, 9:00–18:00.", ar: "يسعد فريقنا بخدمتك من الأحد إلى الخميس، 9:00–18:00." },
  sellText: { en: "Warehouses with a Khazna seller account can list auctions, Buy Now stock and live sales.", ar: "يمكن للمستودعات التي لديها حساب بائع على خزنة عرض المزادات ومنتجات الشراء الفوري والمزادات المباشرة." },
  menuAccount: { en: "Account", ar: "الحساب" },
  paymentMethods: { en: "Payment methods", ar: "طرق الدفع" },

  // Home · hero
  heroFactsLabel: { en: "Why Khazna", ar: "لماذا خزنة" },
  onTheBlock: { en: "On the block", ar: "المعروض الآن" },

  // Home · across the Kingdom
  kingdomEyebrow: { en: "Saudi seller warehouses", ar: "مستودعات البائعين في المملكة" },
  kingdomTitle: { en: "Across the Kingdom", ar: "في أنحاء المملكة" },
  kingdomText: {
    en: "Every seller on Khazna is a warehouse. Choose a city to meet the sellers behind its lots.",
    ar: "كل بائع على خزنة مستودع. اختر مدينة لتتعرّف على البائعين خلف معروضها.",
  },

  // Home · sections
  categoriesEyebrow: { en: "Eight departments", ar: "ثمانية أقسام" },
  endingEyebrow: { en: "Last chance to bid", ar: "الفرصة الأخيرة للمزايدة" },
  featuredEyebrow: { en: "Most bid right now", ar: "الأكثر مزايدة الآن" },
  buyNowEyebrow: { en: "Fixed price, no waiting", ar: "سعر ثابت دون انتظار" },
  gradesEyebrow: { en: "Condition graded", ar: "مصنّف حسب الحالة" },
  gradesTitle: { en: "One clear grade for every lot", ar: "درجة واضحة لكل منتج" },
  fullGuide: { en: "See the full guide", ar: "اطّلع على الدليل الكامل" },
  worksYes: { en: "Works", ar: "يعمل" },
  worksNo: { en: "Not working", ar: "لا يعمل" },
  valuesEyebrow: { en: "Behind the name", ar: "ما وراء الاسم" },
  valuesTitle: { en: "Seven values, one name", ar: "سبع قيم في اسم واحد" },
  valuesText: {
    en: "Each letter of KHAZNAH stands for a principle we hold every auction to.",
    ar: "كل حرف من حروف KHAZNAH يمثّل مبدأً نلتزم به في كل مزاد.",
  },
  trustEyebrow: { en: "Built on trust", ar: "مبنيّة على الثقة" },
  howEyebrow: { en: "Four steps", ar: "أربع خطوات" },
  million: { en: "M", ar: " مليون" },
  liveBandText: {
    en: "A presenter-led sale streamed from the warehouse floor. Bid in real time as each lot comes up.",
    ar: "مزاد يقدّمه مذيع مباشرة من أرض المستودع. زايد لحظياً مع عرض كل منتج.",
  },
  moreEvents: { en: "Coming up", ar: "القادم" },

  // Browse
  browseLead: {
    en: "Graded stock from Saudi warehouses — bid on it, or buy it now.",
    ar: "مخزون مصنّف من مستودعات سعودية — زايد عليه أو اشترِه فوراً.",
  },
  view: { en: "View", ar: "طريقة العرض" },
  saleType: { en: "Sale type", ar: "نوع البيع" },
  applyFilters: { en: "Apply", ar: "تطبيق" },
  anyGrade: { en: "Any grade", ar: "أي درجة" },

  // Product & auction
  highlights: { en: "Highlights", ar: "أبرز المزايا" },
  fullPallet: { en: "Full pallet", ar: "طبلية كاملة" },
  deliveryTitle: { en: "Delivery, pickup & returns", ar: "التوصيل والاستلام والإرجاع" },
  details: { en: "Lot details", ar: "تفاصيل المنتج" },
  unitsInLot: { en: "Units in this lot", ar: "القطع في هذه الدفعة" },
  statusOpen: { en: "Auction open", ar: "المزاد مفتوح" },
  statusUpcoming: { en: "Opens soon", ar: "يُفتح قريباً" },
  endedText: {
    en: "Bidding has closed on this lot. Similar lots are still open below.",
    ar: "أُغلقت المزايدة على هذا المنتج. تجد أدناه منتجات مشابهة ما زالت مفتوحة.",
  },
  soldText: {
    en: "This lot has found its buyer. Similar lots are still open below.",
    ar: "وجد هذا المنتج مشتريه. تجد أدناه منتجات مشابهة ما زالت مفتوحة.",
  },
  paymentWindow: { en: "Payment is due within {n} hours of winning.", ar: "يُستحق الدفع خلال {n} ساعة من الفوز." },
  depositTerm: {
    en: "To bid, your wallet must cover a refundable deposit of {amount}.",
    ar: "للمزايدة، يجب أن يغطي رصيد محفظتك تأميناً مسترداً بقيمة {amount}.",
  },
  youBid: { en: "Your bid", ar: "مزايدتك" },
  bidLeading: { en: "You lead at {amount}. You'll get a notification if someone outbids you.", ar: "أنت في الصدارة بمبلغ {amount}. سيصلك إشعار إذا تجاوز أحد مزايدتك." },
  bidOutbid: { en: "Bid {amount} or more to take the lead again.", ar: "زايد بـ {amount} أو أكثر لتستعيد الصدارة." },
  bidWon: { en: "Payment is due within 24 hours. We've sent the details to your account.", ar: "يُستحق الدفع خلال 24 ساعة، وقد أرسلنا التفاصيل إلى حسابك." },
  bidLost: { en: "Another bidder won this lot. Similar lots are open below.", ar: "فاز مزايد آخر بهذا المنتج. تجد أدناه منتجات مشابهة مفتوحة." },
  bidLostTitle: { en: "You didn't win this auction", ar: "لم تفز بهذا المزاد" },
  proxyActive: { en: "Automatic bidding is on", ar: "المزايدة التلقائية مفعّلة" },
  buyNowBoxText: { en: "Skip the bidding and take it home at a fixed price.", ar: "تجاوز المزايدة واحصل عليه بسعر ثابت." },
  vsMarket: { en: "vs. typical market price", ar: "مقارنةً بسعر السوق المعتاد" },
  bidderCol: { en: "Bidder", ar: "المزايد" },
  amountCol: { en: "Amount", ar: "المبلغ" },
  timeCol: { en: "Time", ar: "الوقت" },
  lineItems: { en: "Line items", ar: "البنود" },
  gradeCol: { en: "Grade", ar: "الدرجة" },
  qtyCol: { en: "Qty", ar: "الكمية" },

  // Live
  liveRoom: { en: "Live auction room", ar: "غرفة المزاد المباشر" },
  feedEmpty: { en: "Waiting for the first bid on this lot…", ar: "بانتظار أول مزايدة على هذا المنتج…" },
  liveWon: { en: "You won the last lot", ar: "فزت بالمنتج السابق" },
  hideLots: { en: "Hide", ar: "إخفاء" },
  showLots: { en: "Show all", ar: "عرض الكل" },
  liveDeposit: { en: "Deposit {amount} · covered by your wallet", ar: "تأمين {amount} · مغطّى من محفظتك" },
  nextUp: { en: "Next up", ar: "التالي" },

  // Seller
  moreSellers: { en: "More seller warehouses", ar: "مستودعات بائعين أخرى" },
  address: { en: "Pickup address", ar: "عنوان الاستلام" },
  hours: { en: "Opening hours", ar: "ساعات العمل" },
  totalListings: { en: "Listings", ar: "المعروضات" },
  categoriesCount: { en: "Categories", ar: "الفئات" },
  storeTrust: { en: "Shop with confidence", ar: "تسوّق بثقة" },
  deliveryAvailable: { en: "Pickup or delivery", ar: "استلام أو توصيل" },
  watchLive: { en: "Watch the live sale", ar: "شاهد المزاد المباشر" },

  // System board
  systemTitle: { en: "Components & states", ar: "المكونات والحالات" },
  systemLead: {
    en: "The building blocks of the Saudi Contemporary direction — tokens, type, geometry and every interactive state, in Arabic and English.",
    ar: "مكوّنات اتجاه «سعودي معاصر» — الألوان والخطوط والهندسة وكل الحالات التفاعلية، بالعربية والإنجليزية.",
  },
  sysColour: { en: "Colour", ar: "الألوان" },
  sysLight: { en: "Limestone · light", ar: "الحجر الجيري · فاتح" },
  sysDark: { en: "Riyadh night · dark", ar: "ليل الرياض · داكن" },
  sysType: { en: "Typography", ar: "الخطوط" },
  sysGeometry: { en: "Brand geometry", ar: "هندسة الهوية" },
  sysDiamond: { en: "Diamond — from the dot of the خ", ar: "المعيّن — من نقطة الخاء" },
  sysChamfer: { en: "62° chamfer — from the stroke of the خ", ar: "الشطف بزاوية 62° — من جرّة الخاء" },
  sysGrid: { en: "Hairline grid — from the square-Kufic wordmark", ar: "الشبكة الدقيقة — من الخط الكوفي المربّع" },
  sysButtons: { en: "Buttons", ar: "الأزرار" },
  sysInputs: { en: "Inputs", ar: "حقول الإدخال" },
  sysBadges: { en: "Badges & grades", ar: "الشارات والدرجات" },
  sysCards: { en: "Cards in every state", ar: "البطاقات بكل حالاتها" },
  sysFeedback: { en: "Feedback & overlays", ar: "التنبيهات والنوافذ" },
  sysNavigation: { en: "Navigation", ar: "التنقل" },
  stDefault: { en: "Default", ar: "افتراضي" },
  stHover: { en: "Hover", ar: "تمرير" },
  stActive: { en: "Active", ar: "نشط" },
  stFocus: { en: "Focus", ar: "تركيز" },
  stDisabled: { en: "Disabled", ar: "معطّل" },
  stLoading: { en: "Loading", ar: "تحميل" },
  stFocused: { en: "Focused", ar: "محدّد" },
  stError: { en: "Error", ar: "خطأ" },
  stNormal: { en: "Listing", ar: "منتج معروض" },
  stAuction: { en: "Auction", ar: "مزاد" },
  stLive: { en: "Live auction", ar: "مزاد مباشر" },
  stEnding: { en: "Ending soon", ar: "ينتهي قريباً" },
  stNew: { en: "New listing", ar: "منتج جديد" },
  stSold: { en: "Sold", ar: "مُباع" },
  stUnavailable: { en: "Unavailable", ar: "غير متاح" },
  stWatched: { en: "Watched", ar: "في قائمة المتابعة" },
  stSkeleton: { en: "Loading skeleton", ar: "هيكل التحميل" },
  stEmpty: { en: "Empty state", ar: "حالة عدم وجود نتائج" },
  toastDemo: { en: "Toasts", ar: "الإشعارات المنبثقة" },
  modalDemo: { en: "Modal", ar: "نافذة حوار" },
  dropdownDemo: { en: "Dropdown", ar: "قائمة منسدلة" },
  drawerDemo: { en: "Filter drawer", ar: "درج عوامل التصفية" },
  menuDemo: { en: "Mobile menu", ar: "قائمة الجوال" },
  paginationDemo: { en: "Pagination & load more", ar: "ترقيم الصفحات وعرض المزيد" },
  openDrawer: { en: "Open filters", ar: "فتح عوامل التصفية" },
  openMenuDemo: { en: "Open the mobile menu", ar: "فتح قائمة الجوال" },
  openModal: { en: "Open the grade guide", ar: "فتح دليل الدرجات" },
  toastSuccess: { en: "Success", ar: "نجاح" },
  toastWarning: { en: "Warning", ar: "تحذير" },
  toastInfo: { en: "Information", ar: "معلومة" },
  toastNeutral: { en: "Neutral", ar: "محايد" },
  swatchNames: {
    "--bg": { en: "Limestone", ar: "الحجر الجيري" },
    "--surface": { en: "Surface", ar: "السطح" },
    "--surface-2": { en: "Sand", ar: "الرملي" },
    "--plate": { en: "Plate", ar: "لوح العرض" },
    "--border": { en: "Hairline", ar: "الخط الرفيع" },
    "--text-primary": { en: "Night indigo", ar: "النيلي الليلي" },
    "--text-secondary": { en: "Ink", ar: "الحبر" },
    "--primary": { en: "Brand indigo", ar: "نيلي الهوية" },
    "--secondary": { en: "Night", ar: "الليلي" },
    "--accent": { en: "Saffron gold", ar: "الذهبي الزعفراني" },
    "--live": { en: "Brick · live", ar: "الطوبي · مباشر" },
    "--success": { en: "Success", ar: "نجاح" },
    "--warning": { en: "Warning", ar: "تنبيه" },
    "--danger": { en: "Error", ar: "خطأ" },
  },
  typeRoles: {
    display: { en: "Display", ar: "العنوان الرئيسي" },
    heading: { en: "Section heading", ar: "عنوان القسم" },
    body: { en: "Body", ar: "النص" },
    figures: { en: "Figures", ar: "الأرقام" },
  },
  typeNotesAr: {
    en: "Display 800 · leading 1.24 — Body 400 · 16.5 px · leading 1.85 — never letter-spaced",
    ar: "العناوين بوزن 800 وتباعد أسطر 1.24 — النص بوزن 400 وحجم 16.5 وتباعد 1.85 — دون تباعد بين الحروف",
  },
  typeNotesEn: {
    en: "Display 700 · width 112% — Body 400 · 16 px · leading 1.65 — echo caps tracked +0.2 em",
    ar: "العناوين بوزن 700 وعرض 112% — النص بوزن 400 وحجم 16 وتباعد 1.65 — أسطر الصدى بأحرف كبيرة متباعدة",
  },
  btnVariants: {
    primary: { en: "Primary", ar: "أساسي" },
    night: { en: "Night", ar: "ليلي" },
    gold: { en: "Saffron", ar: "زعفراني" },
    outline: { en: "Outline", ar: "محدّد" },
    ghost: { en: "Quiet", ar: "هادئ" },
  },
  helperText: { en: "Used to sign in to your account.", ar: "يُستخدم لتسجيل الدخول إلى حسابك." },
  displaySample: { en: "Graded inventory.", ar: "مخزون مصنّف." },
  headingSample: { en: "Ending soon", ar: "تنتهي قريباً" },
  bodySample: {
    en: "Every lot shows its condition grade.",
    ar: "لكل منتج درجة حالة معلنة.",
  },
};

// Plural forms (same shape as data/ui.js PLURALS; Arabic uses all six CLDR forms).
export const COPY_PLURALS = {
  warehouses: {
    en: { one: "{n} warehouse", other: "{n} warehouses" },
    ar: { zero: "لا مستودعات", one: "مستودع واحد", two: "مستودعان", few: "{n} مستودعات", many: "{n} مستودعاً", other: "{n} مستودع" },
  },
  openAuctions: {
    en: { one: "{n} open auction", other: "{n} open auctions" },
    ar: { zero: "لا مزادات مفتوحة", one: "مزاد مفتوح واحد", two: "مزادان مفتوحان", few: "{n} مزادات مفتوحة", many: "{n} مزاداً مفتوحاً", other: "{n} مزاد مفتوح" },
  },
  buyNowItems: {
    en: { one: "{n} Buy Now item", other: "{n} Buy Now items" },
    ar: { zero: "لا منتجات للشراء الفوري", one: "منتج واحد للشراء الفوري", two: "منتجان للشراء الفوري", few: "{n} منتجات للشراء الفوري", many: "{n} منتجاً للشراء الفوري", other: "{n} منتج للشراء الفوري" },
  },
  cases: {
    en: { one: "{n} case", other: "{n} cases" },
    ar: { zero: "لا كراتين", one: "كرتونة واحدة", two: "كرتونتان", few: "{n} كراتين", many: "{n} كرتونة", other: "{n} كرتونة" },
  },
};
