// Concept A — Premium Commerce: copy unique to this concept.
// Shared labels come from data/ui.js through useLang().ui(); everything here
// is specific to A's layouts. The voice is warm, considered and boutique —
// an elevated department store — while staying plain and claims-safe. Arabic
// is written as natural MSA for a Saudi audience, not translated word for word.

export const COPY = {
  // ── Chrome ────────────────────────────────────────────────────────────────
  skipToContent: { en: "Skip to main content", ar: "تخطَّ إلى المحتوى الرئيسي" },
  mainNav: { en: "Main", ar: "القائمة الرئيسية" },
  shortcuts: { en: "Shortcuts", ar: "اختصارات" },
  logoHome: { en: "Khazna — home", ar: "خزنة — الرئيسية" },
  trustNotes: { en: "Why buy on Khazna", ar: "لماذا الشراء عبر خزنة" },
  hello: { en: "Hello, {name}", ar: "أهلاً، {name}" },
  helloGuest: { en: "Hello, sign in", ar: "أهلاً، سجّل الدخول" },
  chooseCity: { en: "Choose your delivery city", ar: "اختر مدينة التوصيل" },
  citySet: { en: "Delivering to {city}", ar: "التوصيل إلى {city}" },
  citySetText: { en: "Delivery is priced for your full address at checkout.", ar: "تُحسب تكلفة التوصيل لعنوانك الكامل عند إتمام الشراء." },
  searchScope: { en: "Search in", ar: "البحث في" },
  clearSearch: { en: "Clear search", ar: "مسح البحث" },
  keyHints: { en: "to navigate · Enter to open · Esc to close", ar: "للتنقل · Enter للفتح · Esc للإغلاق" },
  seeAllResults: { en: "See all results for “{q}”", ar: "عرض كل النتائج عن «{q}»" },
  noSuggestions: { en: "No matching lots yet — press Enter to search everything.", ar: "لا توجد منتجات مطابقة — اضغط Enter للبحث في كل المعروضات." },
  quickLinks: { en: "Quick links", ar: "روابط سريعة" },
  underAnHour: { en: "Ending in under an hour", ar: "تنتهي خلال أقل من ساعة" },
  buyNowDeals: { en: "Buy Now deals", ar: "عروض الشراء الفوري" },
  signOut: { en: "Sign out", ar: "تسجيل الخروج" },
  signedOut: { en: "You're signed out", ar: "تم تسجيل خروجك" },
  signedOutText: { en: "Sign in again any time with your email and password.", ar: "سجّل الدخول مجدداً في أي وقت ببريدك الإلكتروني وكلمة المرور." },
  welcomeBack: { en: "Welcome back, {name}", ar: "مرحباً بعودتك يا {name}" },
  password: { en: "Password", ar: "كلمة المرور" },
  passwordRequired: { en: "Enter your password.", ar: "أدخل كلمة المرور." },
  continue: { en: "Continue", ar: "متابعة" },
  newHere: { en: "New to Khazna?", ar: "جديد على خزنة؟" },
  signInTitle: { en: "Sign in to Khazna", ar: "سجّل الدخول إلى خزنة" },
  signInText: { en: "Bid, buy and track your lots with one account.", ar: "زايد واشترِ وتابع منتجاتك بحساب واحد." },
  myBidsText: { en: "Bids you place appear here with their live status.", ar: "تظهر هنا مزايداتك مع حالتها المباشرة." },
  ordersText: { en: "You have no orders yet.", ar: "لا توجد لديك طلبات بعد." },
  comingSoon: { en: "Available soon", ar: "متاح قريباً" },
  sellText: { en: "List surplus and returned stock from your warehouse with a seller account.", ar: "اعرض فائض مخزونك ومرتجعاتك من مستودعك عبر حساب بائع." },
  helpText: { en: "Answers on bidding, deposits, grades and pickup.", ar: "إجابات حول المزايدة والتأمين والدرجات والاستلام." },
  cartEmptyTitle: { en: "Your cart is empty", ar: "سلتك فارغة" },
  cartEmptyText: { en: "Buy Now items you add will appear here.", ar: "ستظهر هنا منتجات الشراء الفوري التي تضيفها." },
  subtotal: { en: "Subtotal", ar: "المجموع الفرعي" },
  continueShopping: { en: "Continue shopping", ar: "متابعة التسوق" },
  removeItem: { en: "Remove {title}", ar: "إزالة {title}" },
  removedFromCart: { en: "Removed from your cart", ar: "أُزيل من سلتك" },
  checkoutTitle: { en: "Secure checkout", ar: "إتمام شراء آمن" },
  watchlistEmptyTitle: { en: "No saved lots yet", ar: "لا توجد منتجات محفوظة بعد" },
  watchlistEmptyText: { en: "Tap the heart on any lot to follow its price and closing time.", ar: "اضغط على القلب في أي منتج لمتابعة سعره ووقت إغلاقه." },
  browseLots: { en: "Browse lots", ar: "تصفّح المنتجات" },
  shopBuyNow: { en: "Shop Buy Now", ar: "تسوّق الشراء الفوري" },
  closePanel: { en: "Close", ar: "إغلاق" },
  buyerAccount: { en: "Buyer account", ar: "حساب مشترٍ" },
  footerBlurb: {
    en: "A refined Saudi marketplace for graded surplus, returned and liquidation stock — timed auctions, Buy Now and presenter-led live sales from Saudi warehouses.",
    ar: "سوق سعودي راقٍ للمخزون الفائض والمرتجع ودفعات التصفية المصنّفة — مزادات محددة المدة، وشراء فوري، ومزادات مباشرة يقدّمها مقدّمون من مستودعات سعودية.",
  },
  weAccept: { en: "We accept", ar: "نقبل الدفع عبر" },
  newsletterLabel: { en: "Email address", ar: "البريد الإلكتروني" },

  // ── Home ──────────────────────────────────────────────────────────────────
  heroLabel: { en: "The Khazna edit", ar: "مختارات خزنة" },
  slideOf: { en: "{n} of {total}", ar: "{n} من {total}" },
  pauseSlides: { en: "Pause slideshow", ar: "إيقاف العرض المتحرك" },
  playSlides: { en: "Play slideshow", ar: "تشغيل العرض المتحرك" },
  prevSlide: { en: "Previous slide", ar: "الشريحة السابقة" },
  nextSlide: { en: "Next slide", ar: "الشريحة التالية" },
  goToSlide: { en: "Go to slide {n}", ar: "الانتقال إلى الشريحة {n}" },
  featuredLot: { en: "Featured lot", ar: "منتج مميز" },
  palletsTitle: { en: "Bulk pallets, sold as one lot", ar: "طبليات بالجملة تُباع كدفعة واحدة" },
  palletsFrom: { en: "From", ar: "ابتداءً من" },
  palletsBody: {
    en: "Full pallets and sealed cartons with line-by-line manifests — considered lots for resellers, workshops and offices.",
    ar: "طبليات كاملة وكراتين مختومة مع بيان تفصيلي لكل بند — دفعات مدروسة لتجار التجزئة والورش والمكاتب.",
  },
  palletsCta: { en: "Shop bulk & pallets", ar: "تسوّق الجملة والطبليات" },
  palletsPoints: [
    { en: "Line-by-line manifest", ar: "بيان تفصيلي لكل بند" },
    { en: "Condition grade shown", ar: "درجة الحالة ظاهرة" },
    { en: "Pickup or delivery", ar: "استلام أو توصيل" },
  ],
  liveSlideLot: { en: "On the block now", ar: "المعروض الآن" },
  biggestSaving: { en: "Biggest saving today", ar: "أكبر توفير اليوم" },
  shopAllDeals: { en: "Shop all deals", ar: "تسوّق كل العروض" },
  categoriesSubtitle: { en: "Graded stock, curated across eight departments", ar: "مخزون مصنّف، منتقى عبر ثماني فئات" },
  auctionsRailTitle: { en: "Auctions closing soon", ar: "مزادات تُغلق قريباً" },
  auctionsRailSubtitle: {
    en: "Prices update live — a bid in the final 5 minutes extends the clock.",
    ar: "الأسعار تتحدّث مباشرة — والمزايدة في آخر 5 دقائق تمدّد الوقت.",
  },
  liveBandSubtitle: { en: "Presenter-led sales, streamed live from Saudi warehouses", ar: "مزادات يقدّمها مقدّمون، ببث مباشر من مستودعات سعودية" },
  comingUp: { en: "Coming up", ar: "القادم" },
  dealsTitle: { en: "Deals on Buy Now", ar: "عروض الشراء الفوري" },
  dealsSubtitle: { en: "Fixed prices and disclosed grades, ready to ship or collect", ar: "أسعار ثابتة ودرجات معلنة، جاهزة للشحن أو الاستلام" },
  bulkSubtitle: { en: "Pallets and cartons with full manifests, sold as a single lot", ar: "طبليات وكراتين ببيانات كاملة، تُباع كدفعة واحدة" },
  sellersTitle: { en: "Shop by seller", ar: "تسوّق حسب البائع" },
  sellersSubtitle: { en: "A considered selection of Saudi warehouses and outlets", ar: "مجموعة منتقاة من المستودعات والمنافذ السعودية" },
  howSubtitle: { en: "From sign-up to collection in four considered steps", ar: "من التسجيل إلى الاستلام في أربع خطوات مدروسة" },
  gradesTitle: { en: "Condition grades", ar: "درجات الحالة" },
  fullGradeGuide: { en: "Full grade guide", ar: "دليل الدرجات الكامل" },
  statMillion: { en: "{value} million Saudi riyals", ar: "{value} مليون ريال سعودي" },
  step: { en: "Step {n}", ar: "الخطوة {n}" },

  // ── Cards ─────────────────────────────────────────────────────────────────
  fullPallet: { en: "Full pallet · {units}", ar: "طبلية كاملة · {units}" },
  carton: { en: "Carton · {units}", ar: "كرتونة · {units}" },
  viewResult: { en: "View result", ar: "عرض النتيجة" },
  watchItem: { en: "Watch {title}", ar: "متابعة {title}" },
  addItemToCart: { en: "Add {title} to cart", ar: "أضف {title} إلى السلة" },
  bidOnItem: { en: "Bid on {title}", ar: "زايد على {title}" },
  bidWithAmount: { en: "{bids} · {bidders}", ar: "{bids} · {bidders}" },

  // ── Browse ────────────────────────────────────────────────────────────────
  resultsFor: { en: "Results for “{q}”", ar: "نتائج البحث عن «{q}»" },
  quoted: { en: "“{q}”", ar: "«{q}»" },
  resultsLabel: { en: "Results", ar: "النتائج" },
  endingUnderHour: { en: "Ending < 1h", ar: "ينتهي خلال ساعة" },
  removeFilter: { en: "Remove filter: {label}", ar: "إزالة عامل التصفية: {label}" },
  endsWithin: { en: "Ends within {window}", ar: "ينتهي خلال {window}" },
  applyPrice: { en: "Apply", ar: "تطبيق" },
  tryThese: { en: "Popular searches", ar: "عمليات بحث شائعة" },
  saleType: { en: "Sale type", ar: "نوع البيع" },
  viewAs: { en: "View", ar: "طريقة العرض" },
  activeFilters: { en: "Active filters", ar: "عوامل التصفية النشطة" },
  showingRange: { en: "{from}–{to} of {total}", ar: "{from}–{to} من {total}" },
  sortSheet: { en: "Sort lots", ar: "ترتيب المنتجات" },

  // ── Product ───────────────────────────────────────────────────────────────
  highlights: { en: "Highlights", ar: "أبرز المزايا" },
  deliveryReturns: { en: "Delivery & returns", ar: "التوصيل والإرجاع" },
  galleryLabel: { en: "Images of {title}", ar: "صور {title}" },
  quantityLocked: { en: "Full lot", ar: "دفعة كاملة" },
  maxQty: { en: "Maximum available: {n}", ar: "الحد الأقصى المتاح: {n}" },
  lotTotal: { en: "Total", ar: "الإجمالي" },
  inTheBox: { en: "Condition summary", ar: "ملخص الحالة" },
  gradeMatrixWorks: { en: "Works", ar: "يعمل" },
  gradeMatrixNotWorking: { en: "Not working", ar: "لا يعمل" },

  // ── Auction ───────────────────────────────────────────────────────────────
  phaseLive: { en: "Open for bids", ar: "مفتوح للمزايدة" },
  auctionAndBuyNow: { en: "Auction + Buy Now", ar: "مزاد + شراء فوري" },
  auctionProgress: { en: "Auction progress", ar: "تقدّم المزاد" },
  boughtTitle: { en: "It's yours — the auction is closed", ar: "أصبح لك — تم إغلاق المزاد" },
  boughtText: { en: "Choose delivery or pickup at checkout to complete your purchase.", ar: "اختر التوصيل أو الاستلام عند الدفع لإتمام عملية الشراء." },
  boughtBanner: { en: "You bought this lot with Buy Now", ar: "اشتريت هذا المنتج بالشراء الفوري" },
  lostBanner: { en: "Auction closed — you were outbid", ar: "أُغلق المزاد — تمت المزايدة بأعلى منك" },
  upcomingNote: {
    en: "Bidding opens when the countdown ends. Watch the lot to keep it in your watchlist.",
    ar: "تبدأ المزايدة عند انتهاء العد التنازلي. تابع المنتج ليبقى في قائمة متابعتك.",
  },
  amount: { en: "Amount", ar: "المبلغ" },
  time: { en: "Time", ar: "الوقت" },
  termsDeposit: { en: "Refundable bidding deposit of {amount}, covered by your wallet.", ar: "تأمين مزايدة مسترد بقيمة {amount}، مغطّى من محفظتك." },
  termsPayment: { en: "Winning bidders pay within {hours} hours.", ar: "يدفع الفائز خلال {hours} ساعة من إغلاق المزاد." },
  termsIncrement: { en: "Minimum bid increment is {amount}.", ar: "الحد الأدنى للزيادة {amount}." },
  bidSheetTitle: { en: "Place your bid", ar: "قدّم مزايدتك" },
  yourMaxIs: { en: "Your maximum: {amount}", ar: "حدّك الأقصى: {amount}" },
  totalUnits: { en: "{units} across {lines}", ar: "{units} في {lines}" },
  line: { en: "Item", ar: "البند" },
  qty: { en: "Qty", ar: "الكمية" },
  statsBids: { en: "Bids", ar: "المزايدات" },
  statsBidders: { en: "Bidders", ar: "المزايدون" },
  statsWatching: { en: "Watching", ar: "المتابعون" },

  // ── Live ──────────────────────────────────────────────────────────────────
  tabBid: { en: "Bid", ar: "المزايدة" },
  tabLots: { en: "Lots", ar: "المنتجات" },
  status: { en: "Status", ar: "الحالة" },
  lotNo: { en: "No.", ar: "رقم" },
  liveDeposit: { en: "{amount} bidding deposit · covered by your wallet", ar: "تأمين مزايدة {amount} · مغطّى من محفظتك" },
  soldToYou: { en: "Sold to you", ar: "بيع لك" },
  noBidsLive: { en: "Waiting for the opening bid", ar: "بانتظار أول مزايدة" },
  lotClock: { en: "Lot closes in", ar: "يُغلق المنتج خلال" },
  secondsShort: { en: "{n}s", ar: "{n} ث" },

  // ── Seller ────────────────────────────────────────────────────────────────
  storeLive: { en: "Live sale on now", ar: "مزاد مباشر الآن" },
  categoriesCount: { en: "Categories", ar: "الفئات" },
  storeLinkCopied: { en: "Store link copied", ar: "تم نسخ رابط المتجر" },

  // ── System board ──────────────────────────────────────────────────────────
  systemIntro: {
    en: "The Premium Commerce kit: tokens, serif-led type and every interactive state used across the concept.",
    ar: "مكوّنات التجارة الفاخرة: الرموز، والطباعة بحروف مذيّلة، وكل الحالات التفاعلية المستخدمة في هذا المفهوم.",
  },
  systemEyebrow: { en: "Design system", ar: "نظام التصميم" },
  sysColour: { en: "Colour", ar: "الألوان" },
  sysType: { en: "Typography", ar: "الطباعة" },
  sysButtons: { en: "Buttons", ar: "الأزرار" },
  sysInputs: { en: "Inputs & controls", ar: "الحقول وعناصر التحكم" },
  sysBadges: { en: "Badges & status", ar: "الشارات والحالات" },
  sysCards: { en: "Cards", ar: "البطاقات" },
  sysLoading: { en: "Loading & empty", ar: "التحميل والحالة الفارغة" },
  sysFeedback: { en: "Feedback & overlays", ar: "التنبيهات والنوافذ" },
  sysNavigation: { en: "Navigation", ar: "التنقل" },
  sysSurfaces: { en: "Surfaces", ar: "الأسطح" },
  sysText: { en: "Text", ar: "النصوص" },
  sysBrand: { en: "Brand & action", ar: "الهوية والإجراءات" },
  sysStatus: { en: "Status", ar: "الحالات" },
  sysGrades: { en: "Condition grades", ar: "درجات الحالة" },
  stDefault: { en: "Default", ar: "افتراضي" },
  stHover: { en: "Hover", ar: "عند التمرير" },
  stActive: { en: "Active", ar: "نشط" },
  stFocus: { en: "Focus", ar: "عند التركيز" },
  stDisabled: { en: "Disabled", ar: "معطّل" },
  stLoading: { en: "Loading", ar: "قيد التحميل" },
  stFocused: { en: "Focused", ar: "محدد" },
  stError: { en: "Error", ar: "خطأ" },
  vPrimary: { en: "Primary", ar: "أساسي" },
  vSoft: { en: "Soft", ar: "هادئ" },
  vOutline: { en: "Outline", ar: "محدّد" },
  vGhost: { en: "Ghost", ar: "شفاف" },
  vValue: { en: "Value", ar: "قيمة" },
  typeDisplay: { en: "Display", ar: "عنوان رئيسي" },
  typeTitle: { en: "Section title", ar: "عنوان قسم" },
  typeCard: { en: "Card title", ar: "عنوان بطاقة" },
  typeBody: { en: "Body", ar: "نص أساسي" },
  typeMeta: { en: "Caption", ar: "نص توضيحي" },
  typePrice: { en: "Price & timer", ar: "السعر والمؤقت" },
  cardNormal: { en: "Buy Now listing", ar: "منتج شراء فوري" },
  cardAuction: { en: "Auction", ar: "مزاد" },
  cardLive: { en: "Live auction lot", ar: "منتج في مزاد مباشر" },
  cardEnding: { en: "Ending soon", ar: "ينتهي قريباً" },
  cardCritical: { en: "Closing now", ar: "يُغلق الآن" },
  cardNew: { en: "New listing", ar: "منتج جديد" },
  cardSold: { en: "Sold", ar: "مُباع" },
  cardUnavailable: { en: "Out of stock", ar: "نفدت الكمية" },
  cardWatched: { en: "Watched", ar: "في قائمة المتابعة" },
  cardUpcoming: { en: "Upcoming", ar: "قادم" },
  cardCompact: { en: "Compact card", ar: "بطاقة مختصرة" },
  cardListRow: { en: "List row", ar: "صف في القائمة" },
  sysToasts: { en: "Toasts", ar: "الإشعارات المنبثقة" },
  skeletonLoading: { en: "Skeleton loading", ar: "هياكل التحميل" },
  emptyState: { en: "Empty state", ar: "الحالة الفارغة" },
  toastSuccess: { en: "Success toast", ar: "تنبيه نجاح" },
  toastWarning: { en: "Warning toast", ar: "تنبيه تحذير" },
  toastInfo: { en: "Info toast", ar: "تنبيه معلومات" },
  toastNeutral: { en: "Neutral toast", ar: "تنبيه عام" },
  openModal: { en: "Open confirmation modal", ar: "فتح نافذة التأكيد" },
  openDrawer: { en: "Open filter drawer", ar: "فتح لوحة التصفية" },
  openMobileMenu: { en: "Open mobile menu", ar: "فتح قائمة الجوال" },
  demoSearch: { en: "Search", ar: "بحث" },
  demoEmail: { en: "name@company.sa", ar: "name@company.sa" },
  helperText: { en: "Helper text sits under the field.", ar: "يظهر النص المساعد أسفل الحقل." },
  mobileTabBar: { en: "Mobile tab bar", ar: "شريط التبويب للجوال" },
  pagination: { en: "Numbered pagination", ar: "ترقيم الصفحات" },
  loadMoreDemo: { en: "Progressive loading", ar: "التحميل التدريجي" },
  toggles: { en: "Toggles", ar: "مفاتيح التبديل" },
  countdowns: { en: "Countdown pills", ar: "مؤشرات العد التنازلي" },
  lightTheme: { en: "Light", ar: "فاتح" },
  darkTheme: { en: "Dark", ar: "داكن" },
};
