// Section titles and microcopy unique to Concept A's editorial composition.
export const COPY = {
  closingSoon: { en: "Closing soon", ar: "مزادات تُغلق قريباً" },
  closingSoonText: { en: "Final hours on graded lots. Bids in the last five minutes extend the clock.", ar: "الساعات الأخيرة لمنتجات مصنّفة. المزايدة في آخر خمس دقائق تمدّد الوقت." },
  viewAllAuctions: { en: "View all auctions", ar: "عرض كل المزادات" },
  departments: { en: "Browse by department", ar: "تصفّح حسب القسم" },
  departmentsText: { en: "Eight departments, one grading scale.", ar: "ثمانية أقسام، ومقياس درجات واحد." },
  readyToOwn: { en: "Ready to own", ar: "جاهز للاقتناء" },
  readyToOwnText: { en: "Fixed-price lots you can check out today, each with a disclosed condition grade.", ar: "منتجات بسعر ثابت يمكنك شراؤها اليوم، ولكلٍّ منها درجة حالة معلنة." },
  shopBuyNow: { en: "Shop all Buy Now", ar: "تسوّق كل منتجات الشراء الفوري" },
  liveRoom: { en: "The live room", ar: "غرفة المزاد المباشر" },
  liveRoomText: { en: "A presenter walks the warehouse floor; you bid from wherever you are.", ar: "يتجوّل المقدّم في أرض المستودع، وتزايد أنت من أي مكان." },
  gradeTitle: { en: "Know the condition before you bid", ar: "اعرف الحالة قبل أن تزايد" },
  gradeText: {
    en: "Every lot is listed with a condition grade from New to F, and the grade guide explains what each one means. If an item doesn't match its description, you can request a return within the seller's return window.",
    ar: "يُعرض كل منتج بدرجة حالة من «جديد» إلى F، ويشرح دليل الدرجات معنى كل درجة. وإذا لم يطابق المنتج وصفه، يمكنك طلب الإرجاع خلال مدة الإرجاع المحددة لدى البائع.",
  },
  readGuide: { en: "Read the grade guide", ar: "اقرأ دليل الدرجات" },
  palletsTitle: { en: "Whole pallets. Every line itemised.", ar: "طبليات كاملة، وكل بند موضّح." },
  palletsText: {
    en: "Trade buyers can bid on full pallets and cartons with a published manifest — every product line, quantity and grade listed before the first bid.",
    ar: "يمكن لمشتري الجملة المزايدة على طبليات وكراتين كاملة مع بيان منشور — كل بند وكميته ودرجته معلنة قبل أول مزايدة.",
  },
  exploreBulk: { en: "Explore bulk lots", ar: "استكشف منتجات الجملة" },
  sellersTitle: { en: "From Saudi warehouses", ar: "من مستودعات سعودية" },
  sellersText: {
    en: "Every seller on Khazna is a warehouse with a public storefront showing its city and current listings.",
    ar: "كل بائع على خزنة مستودع له متجر عام يعرض مدينته ومعروضاته الحالية.",
  },
  howTitle: { en: "How Khazna works", ar: "كيف تعمل خزنة" },
  statsLine: { en: "Khazna in numbers", ar: "خزنة بالأرقام" },
  lotPlacard: { en: "Featured lot", ar: "منتج مميز" },
  viewLot: { en: "View lot", ar: "عرض المنتج" },
  enterRoom: { en: "Enter the live room", ar: "ادخل غرفة المزاد" },
  searchPrompt: { en: "What are you looking for?", ar: "عمّ تبحث؟" },
  searchHint: { en: "Try a product, a lot number or a department", ar: "جرّب اسم منتج أو رقم منتج أو قسماً" },
  topMatches: { en: "Top matches", ar: "أفضل النتائج" },
  seeAllResults: { en: "See all results", ar: "عرض كل النتائج" },
  aboutLot: { en: "About this lot", ar: "عن هذا المنتج" },
  theSeller: { en: "The seller", ar: "البائع" },
  service: { en: "Delivery & collection", ar: "التوصيل والاستلام" },
  bidPanelTitle: { en: "Bid on this lot", ar: "زايد على هذا المنتج" },
  closesAt: { en: "Closes", ar: "يُغلق" },
  opensIn: { en: "Opens in", ar: "يُفتح خلال" },
  inTheRoom: { en: "In the room", ar: "في الغرفة" },
  lotsInSale: { en: "Order of sale", ar: "ترتيب البيع" },
  otherEvents: { en: "Coming up", ar: "القادم" },
  sellerTrust: { en: "Buying from this seller", ar: "الشراء من هذا البائع" },
  inventory: { en: "Current inventory", ar: "المعروضات الحالية" },
  systemIntro: {
    en: "The building blocks of Concept A — colour, type, controls and every state a lot can be in — shown in both languages.",
    ar: "مكوّنات المفهوم A — الألوان والخطوط وعناصر التحكم وكل حالة يمكن أن يكون عليها المنتج — باللغتين.",
  },
  newsletterDone: { en: "Thank you — you're subscribed.", ar: "شكراً لك — تم اشتراكك." },
  checkoutTitle: { en: "Secure checkout", ar: "إتمام الشراء الآمن" },
  checkoutText: { en: "Choose delivery or pickup, then pay by mada, Visa or Mastercard, or from your wallet.", ar: "اختر التوصيل أو الاستلام، ثم ادفع عبر مدى أو فيزا أو ماستركارد، أو من محفظتك." },
  signInSheet: { en: "Signed in as Faisal Al-Harbi", ar: "تم تسجيل الدخول باسم فيصل الحربي" },
  highlights: { en: "Highlights", ar: "أبرز المزايا" },
  payWith: { en: "Pay with", ar: "ادفع عبر" },
  soldOutText: {
    en: "This item is sold out. Similar items are shown below.",
    ar: "نفدت كمية هذا المنتج. تجد منتجات مشابهة أدناه.",
  },
  total: { en: "Total", ar: "الإجمالي" },
  lotDetails: { en: "Lot details", ar: "تفاصيل المنتج" },
  termsList: [
    { en: "Bids are binding. The highest bid when the clock reaches zero wins the lot.", ar: "المزايدات ملزمة، وتفوز أعلى مزايدة عند انتهاء الوقت." },
    { en: "A bid in the final five minutes extends the auction by five minutes.", ar: "أي مزايدة في آخر خمس دقائق تمدّد المزاد خمس دقائق." },
    { en: "Your wallet balance must cover a refundable bidding deposit before you bid.", ar: "يجب أن يغطي رصيد محفظتك تأمين المزايدة المسترد قبل أن تزايد." },
    { en: "Winning bidders pay within 24 hours, then choose delivery or collection.", ar: "يدفع الفائز خلال 24 ساعة، ثم يختار التوصيل أو الاستلام." },
  ],
  marketCompare: { en: "Against the typical market price", ar: "مقارنةً بسعر السوق المعتاد" },
  closesOn: { en: "Closes {date}", ar: "يُغلق {date}" },
  opensOn: { en: "Opens {date}", ar: "يُفتح {date}" },
  boughtTitle: { en: "It's yours", ar: "أصبح لك" },
  boughtText: { en: "The auction is closed. Choose delivery or pickup at checkout.", ar: "أُغلق المزاد. اختر التوصيل أو الاستلام عند إتمام الشراء." },
  youBoughtThis: { en: "You bought this lot at the Buy Now price", ar: "اشتريت هذا المنتج بسعر الشراء الفوري" },
  soldResult: { en: "Hammered down for", ar: "رسا المزاد على" },
  endedNoSale: { en: "Bidding has closed on this lot.", ar: "أُغلقت المزايدة على هذا المنتج." },
  seeSimilar: { en: "See similar lots", ar: "منتجات مشابهة" },
  customAmount: { en: "Or enter your own amount", ar: "أو أدخل المبلغ الذي تريده" },
  bidsPlaced: { en: "Bids", ar: "المزايدات" },
  depositHeld: { en: "Your wallet needs to cover a {amount} refundable deposit to bid.", ar: "يجب أن يغطي رصيد محفظتك تأميناً مسترداً بقيمة {amount} للمزايدة." },
  walletLine: { en: "Wallet balance", ar: "رصيد المحفظة" },
  cases: { en: "Cases", ar: "الكراتين" },
  lowerBid: { en: "Lower bid by one increment", ar: "خفّض المزايدة بمقدار زيادة واحدة" },
  raiseBid: { en: "Raise bid by one increment", ar: "ارفع المزايدة بمقدار زيادة واحدة" },
  amount: { en: "Amount", ar: "المبلغ" },
  time: { en: "Time", ar: "الوقت" },
  showFewer: { en: "Show fewer", ar: "عرض أقل" },
  showAllBids: { en: "Show all {n} bids", ar: "عرض كل المزايدات ({n})" },
  timeExtendedNote: { en: "Extended by a late bid", ar: "مُدّد بسبب مزايدة متأخرة" },
  confirmPurchase: { en: "Confirm purchase", ar: "تأكيد الشراء" },
  bidding: { en: "Bidding", ar: "المزايدة" },
  liveTitle: { en: "The live room", ar: "غرفة المزاد المباشر" },
  bidOpen: { en: "Bidding open", ar: "المزايدة مفتوحة" },
  hammer: { en: "Hammer", ar: "المطرقة" },
  lotClock: { en: "Lot clock", ar: "وقت المنتج" },
  liveDeposit: { en: "Your {amount} deposit is covered — bid with one tap.", ar: "تأمينك البالغ {amount} مغطّى — زايد بنقرة واحدة." },
  inRoomCount: { en: "{n} in the room", ar: "{n} في الغرفة" },
  youLead: { en: "You're leading this lot", ar: "أنت المتصدر على هذا المنتج" },
  outbidLive: { en: "Outbid — bid again to lead", ar: "تمت المزايدة بأعلى منك — زايد مجدداً" },
  wonLive: { en: "You won the last lot", ar: "فزت بالمنتج السابق" },
  noActivity: { en: "Bids for this lot will appear here.", ar: "ستظهر المزايدات على هذا المنتج هنا." },
  startsOn: { en: "Starts in {time}", ar: "يبدأ خلال {time}" },
  sellerWarehouseText: { en: "A warehouse selling on Khazna, with its own public storefront.", ar: "مستودع يبيع عبر خزنة، وله متجر عام خاص به." },
  categoriesStat: { en: "Departments", ar: "الأقسام" },
  storeEmpty: { en: "Nothing listed here right now", ar: "لا توجد معروضات هنا حالياً" },
  storeEmptyText: { en: "This storefront has no lots in this view. Try another tab or clear the search.", ar: "لا توجد منتجات في هذا العرض. جرّب تبويباً آخر أو امسح البحث." },
  joinSellerLive: { en: "This seller is live now", ar: "هذا البائع في بث مباشر الآن" },
  sysPalette: { en: "Colour", ar: "الألوان" },
  sysPaletteText: {
    en: "Warm paper, ink, Khazna indigo and antique brass. Every colour is a semantic token, so each component renders correctly in light and dark.",
    ar: "ورق دافئ وحبر ونيلي خزنة ونحاس عتيق. كل لون رمز دلالي، لذا يظهر كل مكوّن بشكل صحيح في الوضعين الفاتح والداكن.",
  },
  sysType: { en: "Typography", ar: "الخطوط" },
  sysTypeText: {
    en: "An editorial serif for display, a precise grotesque for data — each paired with an Arabic face drawn for the same voice.",
    ar: "خط بحروف مذيّلة للعناوين وخط دقيق للبيانات — ولكل منهما نظير عربي يحمل النبرة ذاتها.",
  },
  sysButtons: { en: "Buttons", ar: "الأزرار" },
  sysInputs: { en: "Inputs & controls", ar: "الحقول وعناصر التحكم" },
  sysBadges: { en: "Status, grades & toggles", ar: "الحالات والدرجات والمفاتيح" },
  sysCards: { en: "Lot cards in every state", ar: "بطاقات المنتجات بكل حالاتها" },
  sysFeedback: { en: "Loading, empty & feedback", ar: "التحميل والحالة الفارغة والتنبيهات" },
  sysOverlays: { en: "Overlays, menus & paging", ar: "النوافذ والقوائم والتصفح" },
  stateDefault: { en: "Default", ar: "افتراضي" },
  stateHover: { en: "Hover", ar: "تمرير" },
  stateActive: { en: "Active", ar: "نشط" },
  stateFocus: { en: "Focus", ar: "تركيز" },
  stateDisabled: { en: "Disabled", ar: "معطّل" },
  stateLoading: { en: "Loading", ar: "تحميل" },
  stateError: { en: "Error", ar: "خطأ" },
  viewLight: { en: "Light", ar: "فاتح" },
  viewDark: { en: "Dark", ar: "داكن" },
  variantPrimary: { en: "Primary", ar: "أساسي" },
  variantOutline: { en: "Outline", ar: "محدد" },
  variantQuiet: { en: "Quiet", ar: "هادئ" },
  variantBrass: { en: "Brass", ar: "نحاسي" },
  openDialog: { en: "Open a dialog", ar: "فتح نافذة" },
  openGuide: { en: "Open the grade guide", ar: "فتح دليل الدرجات" },
  openDrawer: { en: "Open the filter drawer", ar: "فتح لوحة التصفية" },
  openMenu: { en: "Open the mobile menu", ar: "فتح قائمة الجوال" },
  toasts: { en: "Notifications", ar: "الإشعارات" },
  skeletons: { en: "Loading placeholders", ar: "عناصر التحميل" },
  emptyStateLabel: { en: "Empty results", ar: "نتائج فارغة" },
  numbered: { en: "Numbered pages", ar: "صفحات مرقّمة" },
  progressive: { en: "Progressive loading", ar: "تحميل تدريجي" },
  dropdown: { en: "Dropdown", ar: "قائمة منسدلة" },
  typeDisplay: { en: "Display", ar: "عنوان رئيسي" },
  typeHeading: { en: "Heading", ar: "عنوان" },
  typeBody: { en: "Body", ar: "نص" },
  typeLabel: { en: "Label", ar: "تسمية" },
  typeFigures: { en: "Figures", ar: "الأرقام" },
  sampleDisplay: { en: "Rare finds, fairly priced", ar: "مقتنيات نادرة بأسعار عادلة" },
  sampleBody: {
    en: "Every lot is listed with its condition grade.",
    ar: "يُعرض كل منتج بدرجة حالته.",
  },
  liveLotLabel: { en: "Live auction lot", ar: "منتج في مزاد مباشر" },
  watchedLabel: { en: "Watched", ar: "في قائمة المتابعة" },
  lowStockLabel: { en: "Low stock", ar: "كمية محدودة" },
  handpicked: { en: "Selected this week", ar: "مختارات هذا الأسبوع" },
  wholeCatalogue: { en: "The whole catalogue", ar: "الكتالوج كاملاً" },
};
