// Option 4 — Auction Commerce (Round 3): copy unique to this design.
// Shared marketplace strings live in data/ui.js; shared content (trust
// points, how it works, policy, footer) lives in data/site.js.

export const COPY = {
  skip: { en: "Skip to content", ar: "انتقل إلى المحتوى" },
  home: { en: "Khazna home", ar: "الصفحة الرئيسية لخزنة" },

  // Header & floor switcher
  floor: { en: "Auction floor", ar: "قاعة المزادات" },
  segLive: { en: "Live", ar: "مباشر" },
  segEnding: { en: "Ending", ar: "تنتهي" },
  segUpcoming: { en: "Upcoming", ar: "القادمة" },
  segBuyNow: { en: "Buy Now", ar: "شراء فوري" },
  menu: { en: "Menu", ar: "القائمة" },
  openMenu: { en: "Open menu", ar: "فتح القائمة" },
  close: { en: "Close", ar: "إغلاق" },
  search: { en: "Search", ar: "بحث" },
  searchLabel: { en: "Search auctions and Buy Now", ar: "ابحث في المزادات والشراء الفوري" },
  searchPlaceholder: { en: "Search lots — ending soonest first", ar: "ابحث عن منتجات — الأقرب إغلاقاً أولاً" },
  searchScope: { en: "Search in", ar: "البحث في" },
  scopeAuctions: { en: "Auctions", ar: "المزادات" },
  scopeBuyNow: { en: "Buy Now", ar: "الشراء الفوري" },
  searchAll: { en: "See all results for “{q}”", ar: "عرض كل نتائج «{q}»" },
  searchNone: { en: "No lots match “{q}”.", ar: "لا توجد منتجات تطابق «{q}»." },
  endingFirst: { en: "Ending soonest", ar: "الأقرب إغلاقاً" },
  rules: { en: "How bidding works", ar: "كيف تعمل المزايدة" },
  myBids: { en: "My bids", ar: "مزايداتي" },
  cart: { en: "Cart", ar: "السلة" },
  cartCount: { en: "Cart, {n} items", ar: "السلة، {n} منتج" },
  account: { en: "Account", ar: "الحساب" },
  accountMenu: { en: "Account menu", ar: "قائمة الحساب" },
  hello: { en: "Hello, {name}", ar: "مرحباً، {name}" },
  wallet: { en: "Wallet", ar: "المحفظة" },
  notifications: { en: "Notifications", ar: "الإشعارات" },
  notificationsEmpty: { en: "You're all caught up.", ar: "لا توجد إشعارات جديدة." },
  orders: { en: "Orders", ar: "الطلبات" },
  ordersText: { en: "You have no orders yet.", ar: "لا توجد لديك طلبات بعد." },
  country: { en: "Saudi Arabia", ar: "المملكة العربية السعودية" },
  switchLanguage: { en: "العربية", ar: "English" },
  switchLanguageLabel: { en: "Switch to Arabic", ar: "التبديل إلى الإنجليزية" },
  categories: { en: "Categories", ar: "الفئات" },
  sellers: { en: "Sellers", ar: "البائعون" },
  help: { en: "Help", ar: "المساعدة" },

  // Live stage
  liveStage: { en: "Live auction", ar: "المزاد المباشر" },
  liveNow: { en: "Live now", ar: "مباشر الآن" },
  watching: { en: "{n} watching", ar: "{n} يشاهدون" },
  previous: { en: "Previous", ar: "السابق" },
  now: { en: "Now", ar: "الآن" },
  upNext: { en: "Up next", ar: "التالي" },
  lotOf: { en: "Lot {n} of {total}", ar: "المنتج {n} من {total}" },
  lotShort: { en: "Lot {n}", ar: "المنتج {n}" },
  sold: { en: "Sold", ar: "بيع" },
  notSold: { en: "Not sold", ar: "لم يُبع" },
  startsAt: { en: "Starts at {amount}", ar: "يبدأ من {amount}" },
  biddingOpen: { en: "Bidding open · the auctioneer sets the pace", ar: "المزايدة مفتوحة · يحدد المزاد وتيرتها" },
  goingOnce: { en: "Going once…", ar: "يذهب مرة…" },
  goingTwice: { en: "Going twice…", ar: "يذهب مرتين…" },
  hammer: { en: "Sold — next lot shortly", ar: "بيع — المنتج التالي قريباً" },
  between: { en: "Next lot in {n}s", ar: "المنتج التالي خلال {n} ث" },
  enterRoom: { en: "Enter the room to bid", ar: "ادخل الغرفة للمزايدة" },
  roomNote: { en: "Live bids are placed inside the room, where your deposit is checked.", ar: "تُقدَّم المزايدات المباشرة داخل الغرفة حيث يُتحقق من التأمين." },
  join: { en: "Join", ar: "انضم" },
  presenter: { en: "Presented by", ar: "يقدّمه" },

  // Ending soon
  endingTitle: { en: "Ending soon", ar: "تنتهي قريباً" },
  endingSub: { en: "Every open auction on one clock — each pin is a lot, placed at its closing time.", ar: "كل المزادات المفتوحة على ساعة واحدة — كل دبوس منتج في موعد إغلاقه." },
  windowLabel: { en: "Closing within", ar: "يُغلق خلال" },
  w15: { en: "15 min", ar: "15 دقيقة" },
  w1h: { en: "1 hour", ar: "ساعة" },
  w3h: { en: "3 hours", ar: "3 ساعات" },
  w24h: { en: "24 hours", ar: "24 ساعة" },
  axisNow: { en: "Now", ar: "الآن" },
  timelineLabel: { en: "Closing times, next 24 hours", ar: "مواعيد الإغلاق خلال 24 ساعة" },
  moreInWindow: { en: "+{n} more closing within {w}", ar: "+{n} أخرى تُغلق خلال {w}" },
  noneInWindow: { en: "Nothing closes in this window — try a longer one.", ar: "لا شيء يُغلق خلال هذه المدة — جرّب مدة أطول." },

  // Tickets
  openForBids: { en: "Open for bids", ar: "مفتوح للمزايدة" },
  closesIn: { en: "Closes in {time}", ar: "يُغلق خلال {time}" },
  opensIn: { en: "Opens in {time}", ar: "يفتح خلال {time}" },
  current: { en: "Current", ar: "الحالية" },
  startingAt: { en: "Starts", ar: "يبدأ" },
  bidN: { en: "Bid {amount}", ar: "زايد بـ {amount}" },
  youreWinning: { en: "You're winning", ar: "مزايدتك الأعلى" },
  watch: { en: "Watch", ar: "متابعة" },
  watching2: { en: "Watching", ar: "تتابعه" },
  inStock: { en: "{n} in stock", ar: "{n} متوفرة" },
  soldOut: { en: "Sold out", ar: "نفدت الكمية" },
  wasSave: { en: "was {was} · −{pct}%", ar: "كان {was} · −{pct}%" },
  addToCart: { en: "Add to cart", ar: "أضف إلى السلة" },
  addedToCart: { en: "Added to your cart", ar: "أُضيف إلى سلتك" },
  timedAuction: { en: "Timed auction", ar: "مزاد محدد المدة" },

  // Confirm
  confirmTitle: { en: "Confirm your bid", ar: "أكّد مزايدتك" },
  confirmLine: { en: "You're bidding {amount} on", ar: "ستزايد بـ {amount} على" },
  confirmDeposit: { en: "Bidding deposit {amount} — covered by your wallet ({wallet}); on timed auctions it isn't deducted.", ar: "تأمين المزايدة {amount} — يغطيه رصيد محفظتك ({wallet})؛ ولا يُخصم في المزادات المحددة المدة." },
  confirmBid: { en: "Confirm bid", ar: "تأكيد المزايدة" },
  cancel: { en: "Cancel", ar: "إلغاء" },

  // Sections
  activeTitle: { en: "Active auctions", ar: "مزادات مفتوحة" },
  activeSub: { en: "Bid tickets, soonest close first", ar: "تذاكر المزايدة، الأقرب إغلاقاً أولاً" },
  viewAllN: { en: "View all {n}", ar: "عرض الكل ({n})" },
  upcomingTitle: { en: "Upcoming", ar: "القادمة" },
  upcomingSub: { en: "Timed lots about to open, and the next live sales", ar: "مزادات على وشك الافتتاح، والمزادات المباشرة التالية" },
  liveEvents: { en: "Live events", ar: "المزادات المباشرة" },
  inTime: { en: "in {time}", ar: "خلال {time}" },
  remindMe: { en: "Remind me", ar: "ذكّرني" },
  reminderOn: { en: "Reminder on", ar: "التذكير مفعّل" },
  concept: { en: "Concept", ar: "فكرة" },
  conceptNote: { en: "Concept idea — event reminders aren't available on Khazna yet.", ar: "فكرة تصميمية — تذكيرات المزادات غير متاحة في خزنة بعد." },
  reminderToast: { en: "Reminder set (concept preview)", ar: "تم ضبط التذكير (معاينة فكرة)" },
  buyNowTitle: { en: "Buy Now", ar: "الشراء الفوري" },
  buyNowSub: { en: "Skip the bidding — fixed prices, biggest saving first", ar: "بدون مزايدة — أسعار ثابتة، الأكبر توفيراً أولاً" },
  shopBuyNow: { en: "Shop Buy Now ({n})", ar: "تسوّق الشراء الفوري ({n})" },
  floorTitle: { en: "Categories on the floor", ar: "الفئات في القاعة" },
  floorSub: { en: "Ordered by each category's next closing lot", ar: "مرتبة حسب أقرب منتج يُغلق في كل فئة" },
  nextClose: { en: "next {time}", ar: "التالي خلال {time}" },
  buyOnly: { en: "Buy Now only", ar: "شراء فوري فقط" },
  hostsTitle: { en: "Auction hosts", ar: "مستضيفو المزادات" },
  hostsSub: { en: "Every seller's open lots on one shared time axis", ar: "منتجات كل بائع المفتوحة على محور زمني واحد" },
  laterThisWeek: { en: "+{n} later this week", ar: "+{n} لاحقاً هذا الأسبوع" },
  enterRoomShort: { en: "Enter room", ar: "ادخل الغرفة" },
  sellerPage: { en: "Seller page", ar: "صفحة البائع" },
  howTitle: { en: "How bidding works", ar: "كيف تعمل المزايدة" },
  stepDeposit: { en: "Keep the deposit in your wallet", ar: "احتفظ بالتأمين في محفظتك" },
  stepBid: { en: "Bid, or set a maximum", ar: "زايد أو حدّد حداً أقصى" },
  stepBidText: { en: "Place a bid, or set a maximum and we'll bid for you one increment at a time.", ar: "قدّم مزايدة، أو حدّد حداً أقصى وسنزايد نيابةً عنك بزيادة واحدة في كل مرة." },
  stepExtend: { en: "Late bids extend the clock", ar: "المزايدة المتأخرة تمدّد الوقت" },
  stepPay: { en: "Win and pay", ar: "افز وادفع" },
  stepPayText: { en: "Pay for a timed-auction win within {h} hours.", ar: "ادفع قيمة فوزك في المزاد المحدد المدة خلال {h} ساعة." },
  stepReceive: { en: "Delivery or pickup", ar: "توصيل أو استلام" },
  gradesTitle: { en: "Condition grades", ar: "درجات الحالة" },

  // My bids
  myBidsTitle: { en: "My bids", ar: "مزايداتي" },
  yourBids: { en: "Your bids", ar: "مزايداتك" },
  watchingList: { en: "Watching", ar: "تتابعها" },
  noBids: { en: "Bids you place here appear with their status and time left.", ar: "تظهر هنا مزايداتك مع حالتها والوقت المتبقي." },
  pill: { en: "{n} winning", ar: "{n} مزايدة أعلى" },
  openMyBids: { en: "Open My bids", ar: "فتح مزايداتي" },

  // Cart
  cartEmpty: { en: "Your cart is empty", ar: "سلتك فارغة" },
  subtotal: { en: "Subtotal", ar: "المجموع الفرعي" },
  remove: { en: "Remove", ar: "إزالة" },
  removed: { en: "Removed from your cart", ar: "أُزيل من سلتك" },
  checkoutTitle: { en: "Secure checkout", ar: "إتمام شراء آمن" },

  // Footer
  footerTag: { en: "Graded returns, surplus and pallets from Saudi warehouses.", ar: "مرتجعات وفائض مخزون وطبليات مصنّفة من مستودعات سعودية." },
  weAccept: { en: "We accept", ar: "نقبل" },
};

// Plural forms this design needs beyond data/ui.js.
export const PL = {
  open: {
    en: { one: "{n} open", other: "{n} open" },
    ar: { zero: "لا مزادات مفتوحة", one: "مزاد مفتوح", two: "مزادان مفتوحان", few: "{n} مزادات مفتوحة", many: "{n} مزاداً مفتوحاً", other: "{n} مزاد مفتوح" },
  },
  buy: {
    en: { one: "{n} Buy Now", other: "{n} Buy Now" },
    ar: { zero: "لا شراء فوري", one: "{n} شراء فوري", two: "{n} شراء فوري", few: "{n} شراء فوري", many: "{n} شراء فوري", other: "{n} شراء فوري" },
  },
};
